import {test,expect} from './fixtures.js';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {platformPool,inTenant,tenantQuery} from '../../apps/server/src/db/pools.js';
import {hashPassword} from '../../apps/server/src/security.js';
test('钟房排钟保存与房间警告跨端确认，实时空闲期间继续确认连接有效',async({page,context,request})=>{
 test.setTimeout(120000);assert.equal(process.env.NODE_ENV,'test');assert.equal(new URL(process.env.DATABASE_URL!).pathname,'/za_spa_saas_test');
 const username='clock-ui-'+randomUUID(),password='Clock-UI-Test-347!',code='CLOCK-'+randomUUID().slice(0,8).toUpperCase();await platformPool.query('INSERT INTO platform_users(username,password,name) VALUES($1,$2,$3)',[username,await hashPassword(password),'钟房验收管理员']);const login=await(await request.post('/api/platform/v1/auth/login',{data:{username,password}})).json();
 const created=await(await request.post('/api/platform/v1/merchants',{headers:{Authorization:'Bearer '+login.data.token},data:{code,name:'钟房验收商家'}})).json();expect(created.ok).toBe(true);expect((await(await request.post('/api/merchant/v1/auth/activate',{data:{token:created.data.invite.token,username:'13800138000',password,name:'钟房老板'}})).json()).ok).toBe(true);const auth=await(await request.post('/api/merchant/v1/auth/login',{data:{merchant_code:code,username:'13800138000',password}})).json();let storeId:number|undefined;
 async function api(path:string,data?:any,method='POST'){const result=await(await request.fetch('/api/merchant/v1'+path,{method,headers:{Authorization:'Bearer '+auth.data.token,'Idempotency-Key':randomUUID(),...(storeId?{'X-Store-ID':String(storeId)}:{})},data})).json();expect(result.ok,JSON.stringify(result)).toBe(true);return result.data}
 const store=await api('/stores',{code:'001',name:'钟房一店'});storeId=store.id;const room=await api('/rooms',{room_no:'601'});await api('/rooms',{room_no:'602'});const first=await api('/technicians',{name:'甲技师',code:'01'}),second=await api('/technicians',{name:'乙技师',code:'02'});
 await page.goto('/');await page.getByLabel('商家编号',{exact:true}).fill(code);await page.getByLabel('账号',{exact:true}).fill('13800138000');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/钟房排钟/}).click();await expect(page.getByText('甲技师',{exact:true})).toBeVisible();await page.getByRole('button',{name:'同钟数排钟顺序',exact:true}).click();const order=page.getByRole('dialog',{name:'同钟数排钟顺序'});await order.getByLabel('上移乙技师').click();await order.getByLabel('排钟调整原因',{exact:true}).fill('门店班次调整');await order.getByRole('button',{name:'保存排钟顺序',exact:true}).click();await expect(order).toBeHidden();expect((await api('/technicians/queue-order',undefined,'GET')).rows.map((r:any)=>r.id)).toEqual([second.id,first.id]);
 const terminal=await context.newPage();await terminal.goto('/?room-terminal=1');await terminal.getByLabel('商家编号',{exact:true}).fill(code);await terminal.getByLabel('账号',{exact:true}).fill('13800138000');await terminal.getByLabel('密码',{exact:true}).fill(password);await terminal.getByRole('button',{name:'登录',exact:true}).click();await terminal.getByLabel('报钟房间').selectOption(String(room.id));await expect(terminal.getByText('接收当前所选房间警告',{exact:true})).toBeVisible();
 let polls=0;terminal.on('request',r=>{if(r.method()==='GET'&&r.url().endsWith('/clocks/warnings'))polls++});await expect.poll(()=>polls,{timeout:18000,intervals:[1000]}).toBeGreaterThanOrEqual(5);await expect(terminal.getByText('接收当前所选房间警告',{exact:true})).toBeVisible();
 await page.bringToFront();const warning=page.getByRole('region',{name:'房间警告通知'});await expect(warning.getByRole('button',{name:'全店一键预警',exact:true})).toBeEnabled();const posted=page.waitForResponse(r=>r.url().endsWith('/clocks/warnings/broadcast'));await warning.getByRole('button',{name:'全店一键预警',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});const batch=(await(await posted).json()).data;expect(batch.room_count).toBe(2);
 const notification=terminal.getByRole('alertdialog',{name:'前台房间警告'});await expect(notification).toBeVisible();await notification.getByRole('button',{name:/我已看到/}).click();await expect(notification).toBeHidden();await warning.getByText('查看预警记录',{exact:true}).click();await expect(warning).toContainText('已由账号');
 const rows=await inTenant(created.data.merchant.id,async()=>(await tenantQuery('SELECT room_id,acknowledged_by FROM room_warnings ORDER BY id')).rows);expect(rows.length).toBe(2);expect(rows.find((r:any)=>r.room_id===room.id).acknowledged_by).toBe(auth.data.user.id);
 await terminal.close();
 const techUser=await api('/users',{username:'own-tech',password,name:'甲技师登录'});await api('/users/'+techUser.id+'/grants',{grants:[{store_id:store.id,role:'technician',technician_id:first.id}]},'PUT');
 const technician=await context.newPage();await technician.goto('/');await technician.getByLabel('商家编号',{exact:true}).fill(code);await technician.getByLabel('账号',{exact:true}).fill('own-tech');await technician.getByLabel('密码',{exact:true}).fill(password);await technician.getByRole('button',{name:'登录',exact:true}).click();await expect(technician.getByRole('heading',{name:'技师钟房',exact:true})).toBeVisible();await expect(technician.getByRole('heading',{name:'ZA Thera｜澜序 房间报钟器'})).toBeVisible();await expect(technician.getByRole('button',{name:'+ 新增技师',exact:true})).toHaveCount(0);await expect(technician.getByRole('button',{name:'编辑',exact:true})).toHaveCount(0);await expect(technician.getByText('乙技师',{exact:true})).toHaveCount(0);await technician.getByRole('button',{name:'上班打卡',exact:true}).click();await expect(technician.getByRole('button',{name:'下班打卡',exact:true})).toBeVisible();await technician.close();
});
