import {test,expect,_electron as electron} from './fixtures.js';
import {harness,password} from '../helpers.js';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
test('真实 Windows 设备检测经隔离桥读取，并将检测参数带入门店网关草稿',async()=>{
 test.setTimeout(120000);const h=await harness({closePoolsOnStop:false});let app:any;
 try{
  const a=await h.onboard();app=await electron.launch({args:[resolve('apps/client')],env:{...process.env,NODE_ENV:'test',SAAS_TEST_USER_DATA:resolve('.runtime','discovery-'+randomUUID()),ELECTRON_RENDERER_URL:'http://127.0.0.1:5177'}});
  const page=await app.firstWindow();await page.getByLabel('商家编号',{exact:true}).fill(a.merchant.code);await page.getByLabel('账号',{exact:true}).fill('13800138000');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'门店设置',exact:true}).click();await page.getByRole('button',{name:'设备接口',exact:true}).click();
  let failConfigRead=true;
  await page.route('**/api/merchant/v1/devices',async route=>{if(failConfigRead&&route.request().method()==='GET')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,message:'test: configuration temporarily unavailable'})});else await route.continue()});
  const section=page.getByRole('region',{name:'一键检测设备'});await section.getByRole('button',{name:'一键检测本机设备',exact:true}).click();await expect(section.getByText(/检测时间：/)).toBeVisible({timeout:30000});const setup=page.getByRole('region',{name:'一键保存设备配置'});
  await expect(setup.getByRole('alert')).toContainText('无需重新检测设备');
  await expect(setup.getByRole('button',{name:'一键保存所选配置'})).toBeDisabled();
  const detectionTime=await section.getByText(/检测时间：/).textContent();failConfigRead=false;
  await setup.getByRole('button',{name:'重新读取现有配置'}).click();
  await expect(setup.getByRole('combobox',{name:'一键配置手牌刷牌器'})).toBeEnabled();
  await expect(setup.getByRole('alert')).toHaveCount(0);await expect(section.getByText(/检测时间：/)).toHaveText(detectionTime!);
  const r=await page.evaluate(()=>window.saasDesktop!.detectHardware());expect(r.warnings).toEqual([]);expect(r.devices.length).toBeGreaterThan(0);expect(r.interfaces.length).toBeGreaterThan(0);
  expect(await page.evaluate(()=>typeof (window as any).require)).toBe('undefined');
  await section.getByRole('combobox',{name:'用于门店设备的网卡'}).selectOption(r.interfaces[0].address);await section.getByRole('button',{name:'生成推荐网关配置'}).click();
  const gateway=page.getByRole('region',{name:'门店硬件网关'});await gateway.getByRole('button',{name:'应用检测到的网关参数'}).click();await expect(gateway.getByLabel('门店电脑监听IP')).toHaveValue(r.interfaces[0].address);await expect(gateway.getByLabel('网关监听端口')).toHaveValue(String(r.ports.find(p=>p.available)!.port));
  const scanned=await section.getByText(/检测时间：/).textContent();
  await section.getByRole('button',{name:'重新检测设备变化',exact:true}).click();await expect(gateway.getByRole('button',{name:'应用检测到的网关参数'})).toHaveCount(0);
  await expect(section.getByText(/与上次检测比较：/)).toBeVisible({timeout:30000});await expect(section.getByText(/检测时间：/)).not.toHaveText(scanned!);await expect(section.getByRole('combobox',{name:'用于门店设备的网卡'})).toHaveValue(r.interfaces[0].address);
  await section.getByRole('checkbox',{name:'仅看新增或状态变化'}).check();await section.getByRole('checkbox',{name:'仅看新增或状态变化'}).uncheck();
  const candidate=r.devices.find(d=>d.kind==='serial'&&d.status==='OK'&&d.port);expect(candidate).toBeTruthy();
  const item=section.locator('.border-b').filter({hasText:candidate!.name}).first();await item.getByRole('button',{name:'选为刷牌器，填写资料'}).click();
  const reader=page.getByRole('region',{name:'设备配置表单'});await expect(reader.getByLabel('品牌型号')).toHaveValue(candidate!.name.slice(0,100));await expect(reader.getByRole('combobox')).toHaveValue('serial');await reader.getByRole('button',{name:'取消',exact:true}).click();
  await item.getByRole('button',{name:'选为报钟器，填写资料'}).click();const announcer=page.getByRole('region',{name:'技师房播报器配置'});await announcer.getByRole('button',{name:'应用检测到的报钟器资料'}).click();await expect(announcer.getByLabel('串口名称')).toHaveValue(candidate!.port!);await expect(announcer.getByRole('combobox',{name:'预期通信协议',exact:true})).toHaveValue('unknown');await announcer.getByRole('button',{name:'取消',exact:true}).click();
  const quick=page.getByRole('region',{name:'一键保存设备配置'});
  const choices=await quick.getByRole('combobox',{name:'一键配置手牌刷牌器'}).locator('option').evaluateAll((options:HTMLOptionElement[])=>options.filter(o=>o.value!==''&&!o.disabled).map(o=>o.value));expect(choices.length).toBeGreaterThan(1);
  await quick.getByRole('combobox',{name:'一键配置手牌刷牌器'}).selectOption(choices[0]);
  const speakers=await quick.getByRole('combobox',{name:'一键配置技师房报钟器'}).locator('option').evaluateAll((options:HTMLOptionElement[])=>options.filter(o=>o.value!==''&&!o.disabled).map(o=>o.value));expect(speakers.length).toBeGreaterThan(0);await quick.getByRole('combobox',{name:'一键配置技师房报钟器'}).selectOption(speakers[0]);
  let writes=0;page.on('request',(r:any)=>{if(r.method()==='POST'&&r.url().endsWith('/devices/configure'))writes++});
  await quick.getByRole('button',{name:'一键保存所选配置'}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});await expect(quick.getByRole('status')).toContainText('已保存 2 项配置');expect(writes).toBe(1);
  const stored=await h.api(a.token,a.stores[0].id,'/devices');expect(stored.data).toHaveLength(2);expect(stored.data.every((d:any)=>d.status==='not_connected')).toBe(true);
  await quick.getByRole('combobox',{name:'一键配置手牌刷牌器'}).selectOption(choices[0]);await expect(quick.getByRole('button',{name:'一键保存所选配置'})).toBeDisabled();await expect(quick.getByRole('checkbox',{name:'已核对，允许更新以上已有配置'})).not.toBeChecked();
  const oldReader=stored.data.find((d:any)=>d.kind==='wristband_reader');
  const changed=await h.api(a.token,a.stores[0].id,'/devices/wristband_reader','PUT',{version:oldReader.version,name:'另一终端修改',model:oldReader.model,transport:oldReader.transport});expect(changed.ok).toBe(true);
  failConfigRead=true;await quick.getByRole('checkbox',{name:'已核对，允许更新以上已有配置'}).check();await quick.getByRole('button',{name:'一键保存所选配置'}).click();
  await expect(quick.getByRole('alert')).toContainText('无需重新检测设备');await expect(quick.getByRole('button',{name:'一键保存所选配置'})).toBeDisabled();
  failConfigRead=false;await quick.getByRole('button',{name:'重新读取现有配置'}).click();
  await expect(quick.getByRole('checkbox',{name:'已核对，允许更新以上已有配置'})).not.toBeChecked();
  await expect(quick.getByRole('combobox',{name:'一键配置手牌刷牌器'})).toHaveValue(choices[0]);
  await quick.getByRole('checkbox',{name:'已核对，允许更新以上已有配置'}).check();await quick.getByRole('button',{name:'一键保存所选配置'}).click();await expect(quick.getByRole('status')).toContainText('已保存 2 项配置');
  const recovered=await h.api(a.token,a.stores[0].id,'/devices');expect(recovered.data.find((d:any)=>d.kind==='wristband_reader').version).toBe(oldReader.version+2);
  await page.screenshot({path:'.runtime/discovery-desktop.png',fullPage:true});
 }finally{if(app)await app.close();await h.stop()}
});
