import {test,expect} from './fixtures.js';
import type {APIRequestContext,Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {platformPool,inTenant,tenantQuery} from '../../apps/server/src/db/pools.js';
import {hashPassword} from '../../apps/server/src/security.js';
import {readFile} from 'node:fs/promises';

test('设置手牌固定绑定与押金，房态读卡只查询真实绑定且不自动开房',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request),room=await f.api('/rooms',{room_no:'CARD-UI'},f.from.id);await f.api('/wristbands',{code:'0012'},f.from.id);
 await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/门店设置/}).click();await expect(page.getByRole('button',{name:'恢复备份',exact:false})).toHaveCount(0);await page.getByRole('button',{name:'手牌管理',exact:true}).click();
 const row=page.getByRole('row').filter({hasText:'0012'});await row.getByRole('button',{name:'配置固定绑定',exact:true}).click();const dialog=page.getByRole('dialog',{name:'固定房间绑定：0012',exact:true});await dialog.getByRole('combobox').selectOption(String(room.id));await dialog.getByLabel('手牌芯片卡号',{exact:true}).fill('00000012');await dialog.getByLabel('手牌绑定原因',{exact:true}).fill('测试固定绑定');await dialog.getByRole('button',{name:'保存固定绑定',exact:true}).click();await expect(dialog).toBeHidden();await expect(row).toContainText('CARD-UI');
 await row.getByRole('spinbutton').fill('25');await row.getByRole('spinbutton').blur();await expect(page.getByText('手牌 0012 押金已设为 ¥25',{exact:true})).toBeVisible();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/房态/}).click();await page.getByRole('button',{name:'刷手牌查房',exact:true}).click();await page.getByLabel('刷卡原始值',{exact:true}).fill('00000012');await page.getByRole('button',{name:'查询对应房间',exact:true}).click();await expect(page.getByText('手牌 0012 → CARD-UI',{exact:true})).toBeVisible();
 expect(await inTenant(f.merchantId,async()=>(await tenantQuery('SELECT count(*)::int n FROM orders WHERE room_id=$1',[room.id])).rows[0].n)).toBe(0);
});

test('沉睡会员唤醒发券丢响应后原请求核对，重复点击只发一张',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('button',{name:'智能分群',exact:true}).click();await page.getByRole('button',{name:'唤醒会员发券',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'唤醒会员发券',exact:true}),keys:string[]=[];let lose=true;
 await page.route('**/api/merchant/v1/members/wake',async route=>{keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();if(lose){lose=false;await route.abort()}else await route.fulfill({response})});
 await dialog.getByRole('button',{name:'确认批量发券',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click()});await expect(dialog.getByRole('button',{name:'核对原请求',exact:true})).toBeVisible();await expect(dialog.getByLabel('券面额（元）',{exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'核对原请求',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('已发放 1 张');expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);
 expect(await inTenant(f.merchantId,async()=>(await tenantQuery("SELECT count(*)::int n FROM coupons WHERE member_id=$1 AND name='老友回归唤醒券'",[f.member.id])).rows[0].n)).toBe(1);
});

test('门店核验发出专属领券链接，顾客领取后刷新不重复发券',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/门店设置/}).click();await page.getByRole('button',{name:'领券中心',exact:true}).click();await page.getByRole('button',{name:'新增领券活动',exact:true}).click();
 const form=page.getByRole('dialog',{name:'领券活动配置',exact:true});await form.getByLabel('活动名称',{exact:true}).fill('到店核验礼遇');await form.getByLabel('券面值',{exact:true}).fill('20');await form.getByLabel('消费门槛',{exact:true}).fill('68');await form.getByLabel('启用领券活动',{exact:true}).check();await form.getByRole('button',{name:'保存活动',exact:true}).click();await expect(form).toBeHidden();
 await page.getByRole('row').filter({hasText:'到店核验礼遇'}).getByRole('button',{name:'核验并生成领券链接',exact:true}).click();const verify=page.getByRole('dialog',{name:'核验会员并生成领券链接',exact:true});await verify.getByLabel('查找会员',{exact:true}).fill('权益验收会员');await verify.getByRole('button',{name:'查询会员',exact:true}).click();await verify.getByRole('combobox',{name:'待核验会员',exact:true}).selectOption(String(f.member.id));await verify.getByLabel('已在门店核对会员身份与卡号',{exact:true}).check();await verify.getByLabel('核验记录',{exact:true}).fill('测试现场核验记录');await verify.getByRole('button',{name:'生成专属领券链接',exact:true}).click();await expect(verify.getByLabel('专属领券链接',{exact:true})).toBeVisible();
 const url=new URL(await verify.getByLabel('专属领券链接',{exact:true}).inputValue());await page.goto(url.pathname+url.hash);await expect(page.getByRole('button',{name:'确认领取',exact:true})).toBeVisible();await expect(page).not.toHaveURL(/#claim=/);await page.getByRole('button',{name:'确认领取',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click()});await expect(page.getByRole('status')).toHaveText('优惠券已领取');await page.reload();await expect(page.getByRole('status')).toHaveText('优惠券已领取');
 expect(await inTenant(f.merchantId,async()=>(await tenantQuery('SELECT count(*)::int n FROM coupons WHERE member_id=$1',[f.member.id])).rows[0].n)).toBe(1);
});

test('巡房丢响应保留原请求，多次点击只落一条记录',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.api('/rooms',{room_no:'PATROL-UI'},f.from.id);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/房态/}).click();await page.getByRole('button',{name:'巡房',exact:true}).click();
 const keys:string[]=[];let lose=true;await page.route('**/api/merchant/v1/patrol',async route=>{keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();expect(response.ok()).toBe(true);if(lose){lose=false;await route.abort('failed')}else await route.fulfill({response})});
 await page.getByRole('button',{name:'PATROL-UI 空闲',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});await expect(page.getByRole('button',{name:'核对原巡房结果',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'PATROL-UI 空闲',exact:true})).toBeDisabled();await page.getByRole('button',{name:'核对原巡房结果',exact:true}).click();await expect(page.getByText('今日已巡 1 间 · 异常 0 间')).toBeVisible();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);expect(await inTenant(f.merchantId,async()=>(await tenantQuery('SELECT count(*)::int n FROM patrol_log')).rows[0].n)).toBe(1);
});

test('店长从会员页面核验领券，不获得活动配置权限',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);const user=await f.api('/users',{username:'coupon-manager',password:f.password,name:'店长'});await f.api('/users/'+user.id+'/grants',{grants:[{store_id:f.from.id,role:'manager'}]},undefined,'PUT');await f.api('/coupon-campaigns',{version:0,name:'店长核验活动',type:'cash',value:20,min_amount:0,expire_days:7,active:true,max_claims:10},f.from.id);
 await page.goto('/');await page.getByLabel('商家编号',{exact:true}).fill(f.code);await page.getByLabel('账号',{exact:true}).fill('coupon-manager');await page.getByLabel('密码',{exact:true}).fill(f.password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/会员管理/}).click();await page.getByRole('button',{name:'到店领券',exact:true}).click();await expect(page.getByRole('row').filter({hasText:'店长核验活动'})).toBeVisible();await expect(page.getByRole('button',{name:'新增领券活动',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'编辑活动',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'核验并生成领券链接',exact:true}).click();const dialog=page.getByRole('dialog',{name:'核验会员并生成领券链接',exact:true});await dialog.getByLabel('查找会员',{exact:true}).fill('权益验收会员');await dialog.getByRole('button',{name:'查询会员',exact:true}).click();await dialog.getByRole('combobox',{name:'待核验会员',exact:true}).selectOption(String(f.member.id));await dialog.getByLabel('已在门店核对会员身份与卡号',{exact:true}).check();await dialog.getByLabel('核验记录',{exact:true}).fill('现场核验');await dialog.getByRole('button',{name:'生成专属领券链接',exact:true}).click();await expect(dialog.getByLabel('专属领券链接',{exact:true})).toBeVisible();
});

test('平台补发和撤销老板邀请，旧链接不能激活',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request),code='NEW-'+randomUUID().slice(0,8).toUpperCase();await page.clock.setFixedTime(new Date('2025-01-01T00:00:00Z'));await page.goto('/platform');await page.evaluate(token=>sessionStorage.setItem('za-spa-saas:platform-session:v1',token),f.platformToken);await page.reload();await page.getByLabel('商家编号',{exact:true}).fill(code);await page.getByLabel('商家名称',{exact:true}).fill('新店邀请验收');await page.getByRole('button',{name:'开通并生成老板邀请',exact:true}).click();await expect(page.getByLabel('老板邀请链接',{exact:true})).toBeVisible();const old=await page.getByLabel('老板邀请链接',{exact:true}).inputValue();await page.getByRole('navigation',{name:'平台导航'}).getByRole('button',{name:'商家管理',exact:true}).click();await page.getByLabel('搜索商家').fill(code);await page.getByRole('button',{name:'搜索',exact:true}).click();await page.getByRole('row').filter({hasText:code}).getByRole('button',{name:'老板邀请',exact:true}).click();const dialog=page.getByRole('dialog',{name:'老板邀请：新店邀请验收',exact:true});await dialog.getByRole('button',{name:'补发老板邀请',exact:true}).click();await expect(dialog.getByLabel('补发老板邀请链接',{exact:true})).toBeVisible();const next=await dialog.getByLabel('补发老板邀请链接',{exact:true}).inputValue();expect(next).not.toBe(old);await dialog.getByRole('button',{name:'撤销当前邀请',exact:true}).click();await expect(dialog.getByText('已过期',{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'撤销当前邀请',exact:true})).toBeDisabled();for(const link of [old,next]){const response=await request.post('/api/merchant/v1/auth/activate',{data:{token:new URL(link).searchParams.get('token'),username:'owner',password:f.password,name:'老板'}});expect(response.status()).toBe(400)}
});

test('维护日志展示真实请求，按来源筛选并导出脱敏记录',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/门店设置/}).click();await page.getByRole('button',{name:'维护日志',exact:true}).click();const center=page.getByRole('region',{name:'维护日志中心',exact:true});await expect(center.getByRole('row').filter({hasText:'/api/merchant/v1/members'}).first()).toBeVisible();await center.getByRole('row').filter({hasText:'/api/merchant/v1/members'}).first().getByRole('button',{name:'查看详情',exact:true}).click();const detail=page.getByRole('dialog',{name:'维护日志详情',exact:true});await expect(detail).toContainText('/api/merchant/v1/members');await expect(detail).not.toContainText('权益验收会员');await detail.getByRole('button',{name:'关闭维护日志详情',exact:true}).click();await center.getByRole('combobox',{name:'日志来源',exact:true}).selectOption('audit');await center.getByRole('button',{name:'查询日志',exact:true}).click();await expect(center.getByText(/敏感审计 · 本页/)).toBeVisible();const downloading=page.waitForEvent('download');await center.getByRole('button',{name:'导出筛选结果',exact:true}).click();const file=await downloading,data=JSON.parse(await readFile((await file.path())!,'utf8'));expect(data.source).toBe('audit');expect(data.rows.length).toBeGreaterThan(0);expect(JSON.stringify(data)).not.toContain('权益验收会员');
});

test('顾客预约丢响应后刷新页面，原请求恢复并只占一个名额',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.api('/rooms',{room_no:'PUBLIC1',capacity:2},f.from.id);const item=await f.api('/items',{name:'顾客预约项目',type:'service',price:100,duration:60},f.from.id);
 await page.goto('/customer/'+f.code+'/'+f.from.code+'/booking');await page.getByLabel('您的称呼',{exact:true}).fill('顾客页面验收');await page.getByLabel('手机号码',{exact:true}).fill('13900004567');await page.getByRole('combobox',{name:'预约项目',exact:true}).selectOption(String(item.id));
 const future=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(Date.now()+86400000)).replace(' ','T');await page.getByLabel('预约时间（北京时间）',{exact:true}).fill(future);await page.getByRole('button',{name:'查看时段与价格',exact:true}).click();await expect(page.getByRole('button',{name:'确认预约',exact:true})).toBeVisible();
 let lose=true;const keys:string[]=[];await page.route('**/booking/reservations',async route=>{keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();expect(response.ok()).toBe(true);if(lose){lose=false;await route.abort('failed')}else await route.fulfill({response})});
 await page.getByRole('button',{name:'确认预约',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click()});await expect(page.getByRole('button',{name:'核对原操作结果',exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel('您的称呼',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'核对原操作结果',exact:true}).click();await expect(page.getByRole('status')).toHaveText('预约已确认');expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);
 expect(await inTenant(f.merchantId,async()=>(await tenantQuery("SELECT count(*)::int n FROM reservations WHERE customer_name='顾客页面验收'")).rows[0].n)).toBe(1);
 await page.getByRole('button',{name:'取消预约',exact:true}).click();await expect(page.getByRole('status')).toHaveText('已取消');
});

test('设备预留配置可保存并保留未接入状态',async({page,request})=>{
 const f=await fixture(request);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/门店设置/}).click();await page.getByRole('button',{name:'设备接口',exact:true}).click();
 await page.getByRole('button',{name:'配置小票打印机',exact:true}).click();const form=page.getByRole('region',{name:'设备配置表单'});await form.getByLabel('设备名称',{exact:true}).fill('收银前台打印机');await form.getByLabel('品牌型号',{exact:true}).fill('型号待定');await form.getByRole('button',{name:'保存设备配置',exact:true}).click();await expect(form).toBeHidden();await expect(page.getByRole('status').filter({hasText:'设备配置已保存'})).toContainText('驱动尚未接入');await expect(page.getByText('收银前台打印机 · 型号待定',{exact:true})).toBeVisible();
 const rows=await inTenant(f.merchantId,()=>tenantQuery('SELECT name,model,version FROM device_connections WHERE store_id=$1',[f.from.id]));expect(rows.rows).toEqual([{name:'收银前台打印机',model:'型号待定',version:1}]);
 await page.getByRole('button',{name:'配置房间触控面板（点钟王）',exact:true}).click();
 await expect(form).toContainText('不是单台设备注册');await expect(form.getByLabel('预期连接方式')).toHaveValue('unknown');
 await form.getByLabel('品牌型号',{exact:true}).fill('思软 7plus 待确认');await form.getByRole('button',{name:'保存设备配置',exact:true}).click();await expect(form).toBeHidden();
 await page.reload();await page.getByRole('button',{name:'配置房间触控面板（点钟王）',exact:true}).click();await expect(form.getByLabel('品牌型号',{exact:true})).toHaveValue('思软 7plus 待确认');await expect(page.getByText('待厂商协议 · 未接入',{exact:true})).toBeVisible();
});

test('营销配置校验保留输入，丢响应锁定并原键重试，扫描真实发券一次',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();
 await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/门店设置/}).click();await page.getByRole('button',{name:'自动营销',exact:true}).click();
 await page.getByRole('row').filter({hasText:'新客未到店关怀'}).getByRole('button',{name:'配置',exact:true}).click();const form=page.getByRole('dialog',{name:'配置自动营销',exact:true});
 await form.getByLabel('启用工作流',{exact:true}).check();await form.getByLabel('延迟天数',{exact:true}).fill('0');await form.getByLabel('券金额',{exact:true}).fill('-1');await form.getByRole('button',{name:'保存工作流',exact:true}).click();await expect(form.getByRole('alert')).toContainText('券金额须大于零');await expect(form.getByLabel('券金额',{exact:true})).toHaveValue('-1');await form.getByLabel('券金额',{exact:true}).fill('20');
 let lose=true;const keys:string[]=[];await page.route('**/marketing/workflows/new_member_no_visit',async route=>{keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();expect(response.ok()).toBe(true);if(lose){lose=false;await route.abort('failed')}else await route.fulfill({response})});
 await form.getByRole('button',{name:'保存工作流',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click()});await expect(form.getByRole('button',{name:'原请求重试',exact:true})).toBeVisible();await expect(form.getByLabel('券金额',{exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(form).toBeVisible();await form.getByRole('button',{name:'原请求重试',exact:true}).click();await expect(form).toBeHidden();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);
 await page.getByRole('button',{name:'立即扫描',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'扫描完成'})).toContainText('发券 1 张');await page.getByRole('button',{name:'立即扫描',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'扫描完成'})).toContainText('发券 0 张');
 expect(await inTenant(f.merchantId,async()=>(await tenantQuery('SELECT count(*)::int n FROM coupons WHERE member_id=$1',[f.member.id])).rows[0].n)).toBe(1);
});

test('老板导出真实经营记录，截断响应拒绝下载，完整重试校验后生成文件',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.api('/members/recharge',{customer_id:f.member.id,amount:42},f.from.id);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'商家管理',exact:false}).click();
 let downloads=0;page.on('download',()=>downloads++);
 await page.route('**/exports/business',async route=>{const response=await route.fetch();const lines=(await response.text()).trimEnd().split('\n');lines.pop();await route.fulfill({status:200,contentType:'application/x-ndjson',body:lines.join('\n')+'\n'})});
 await page.getByRole('button',{name:'导出全部经营数据',exact:true}).click();await expect(page.getByRole('alert')).toContainText('导出未完整接收');expect(downloads).toBe(0);await page.unrouteAll({behavior:'wait'});
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'导出全部经营数据',exact:true}).click();const file=await downloading;const contents=await readFile((await file.path())!,'utf8');const rows=contents.trimEnd().split('\n').map(line=>JSON.parse(line));expect(rows[0].merchant.id).toBe(f.merchantId);expect(rows.find(r=>r.dataset==='members'&&r.data.id===f.member.id).data.balance).toBe(42);expect(rows.at(-1).type).toBe('complete');expect(downloads).toBe(1);
});

test('充值丢响应时锁定金额和关闭操作，原请求核对只产生一次收款与权益',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.login(page);
 await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();
 await page.getByRole('row').filter({hasText:'权益验收会员'}).getByRole('button',{name:'充值',exact:true}).click();
 const form=page.getByRole('dialog',{name:'会员充值：权益验收会员',exact:true});
 await form.getByLabel('本次充值实收金额').fill('80');await form.getByLabel('本次充值赠送金额').fill('8');
 const keys:string[]=[];let lose=true;
 await page.route('**/members/recharge',async route=>{keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();expect(response.ok()).toBe(true);if(lose){lose=false;await route.abort('failed')}else await route.fulfill({response})});
 await form.getByRole('button',{name:'确认充值',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});
 await expect(form.getByRole('button',{name:'核对原充值结果',exact:true})).toBeVisible();await expect(form.getByLabel('本次充值实收金额')).toBeDisabled();await expect(form.getByLabel('本次充值赠送金额')).toBeDisabled();await expect(form.getByRole('button',{name:'取消',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(form).toBeVisible();
 await form.getByRole('button',{name:'核对原充值结果',exact:true}).click();await expect(form).toBeHidden();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);
 const result=await inTenant(f.merchantId,async()=>({member:(await tenantQuery('SELECT balance,bonus_balance FROM members WHERE id=$1',[f.member.id])).rows[0],postings:(await tenantQuery("SELECT e.amount,e.method FROM shift_entries e JOIN asset_operations a ON a.id=e.asset_operation_id WHERE a.member_id=$1 AND e.kind='recharge'",[f.member.id])).rows}));
 expect(result.member).toEqual({balance:80,bonus_balance:8});expect(result.postings).toEqual([{amount:80,method:'现金'}]);
});
test('充值响应丢失后重新加载恢复原金额和请求键，核对不重复入账',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('row').filter({hasText:'权益验收会员'}).getByRole('button',{name:'充值',exact:true}).click();let form=page.getByRole('dialog',{name:'会员充值：权益验收会员',exact:true});await form.getByLabel('本次充值实收金额').fill('88');await form.getByLabel('本次充值赠送金额').fill('8');
 const keys:string[]=[];let first=true;await page.route('**/members/recharge',async route=>{keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();expect(response.ok()).toBe(true);if(first){first=false;await route.abort('failed')}else await route.fulfill({response})});await form.getByRole('button',{name:'确认充值',exact:true}).click();await expect(form.getByRole('button',{name:'核对原充值结果',exact:true})).toBeVisible();
 await page.reload();form=page.getByRole('dialog',{name:'会员充值：权益验收会员',exact:true});await expect(form).toBeVisible();await expect(form.getByLabel('本次充值实收金额')).toHaveValue('88');await expect(form.getByLabel('本次充值实收金额')).toBeDisabled();await form.getByRole('button',{name:'核对原充值结果',exact:true}).click();await expect(form).toBeHidden();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);const member=await f.api('/members/'+f.member.id,undefined,f.from.id,'GET');expect(member.balance).toBe(88);expect(member.bonus_balance).toBe(8);expect(member.transactions.filter((r:any)=>r.type==='recharge')).toHaveLength(1);expect(await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('za-spa-saas:pending-recharge:')))).toHaveLength(0);
});

test('充值已落库但网关返回 502，保留原请求核对且不重复登记',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);await f.login(page);await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('row').filter({hasText:'权益验收会员'}).getByRole('button',{name:'充值',exact:true}).click();const form=page.getByRole('dialog',{name:'会员充值：权益验收会员',exact:true});await form.getByLabel('本次充值实收金额').fill('66');const keys:string[]=[];let first=true;await page.route('**/members/recharge',async route=>{keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();expect(response.ok()).toBe(true);if(first){first=false;await route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({ok:false,code:'BAD_GATEWAY',message:'Gateway response lost'})})}else await route.fulfill({response})});await form.getByRole('button',{name:'确认充值',exact:true}).click();await expect(form.getByRole('button',{name:'核对原充值结果',exact:true})).toBeVisible();await expect(form.getByLabel('本次充值实收金额')).toBeDisabled();await form.getByRole('button',{name:'核对原充值结果',exact:true}).click();await expect(form).toBeHidden();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);const member=await f.api('/members/'+f.member.id,undefined,f.from.id,'GET');expect(member.balance).toBe(66);expect(member.transactions.filter((r:any)=>r.type==='recharge')).toHaveLength(1);
});

async function fixture(request:APIRequestContext){
 assert.equal(process.env.NODE_ENV,'test');assert.equal(new URL(process.env.DATABASE_URL!).pathname,'/za_spa_saas_test');
 const username='member-ui-'+randomUUID(),password='Member-UI-Test-987!',code='MEM-'+randomUUID().slice(0,8).toUpperCase();
 await platformPool.query('INSERT INTO platform_users(username,password,name) VALUES($1,$2,$3)',[username,await hashPassword(password),'会员验收管理员']);
 const platform=(await(await request.post('/api/platform/v1/auth/login',{data:{username,password}})).json()).data;
 const created=await(await request.post('/api/platform/v1/merchants',{headers:{Authorization:'Bearer '+platform.token},data:{code,name:'澜序会员验收',member_mode:'merchant'}})).json();expect(created.ok).toBe(true);
 expect((await(await request.post('/api/merchant/v1/auth/activate',{data:{token:created.data.invite.token,username:'13800138000',password,name:'会员老板'}})).json()).ok).toBe(true);
 const auth=(await(await request.post('/api/merchant/v1/auth/login',{data:{merchant_code:code,username:'13800138000',password}})).json()).data;
 async function api(path:string,data?:unknown,store?:number,method='POST',token=auth.token){const result=await(await request.fetch('/api/merchant/v1'+path,{method,headers:{Authorization:'Bearer '+token,'Idempotency-Key':randomUUID(),...(store?{'X-Store-ID':String(store)}:{})},data})).json();expect(result.ok,JSON.stringify(result)).toBe(true);return result.data}
 const from=await api('/stores',{code:'001',name:'江畔店（验收）'}),to=await api('/stores',{code:'002',name:'山麓店（验收）'}),member=await api('/members',{name:'权益验收会员'},from.id);
 async function login(page:Page){await page.goto('/');await page.getByLabel('商家编号',{exact:true}).fill(code);await page.getByLabel('账号',{exact:true}).fill('13800138000');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/会员管理/}).click();await page.getByRole('row').filter({hasText:'权益验收会员'}).getByRole('button',{name:'详情',exact:true}).click()}
 return {api,login,from,to,member,merchantId:created.data.merchant.id,password,code,platformToken:platform.token};
}
test('会员四类权益调整保留失败输入，多店更新拒绝旧快照，丢响应按原请求恢复且只落账一次',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request),crashes:string[]=[];page.on('pageerror',e=>crashes.push(e.message));await f.api('/members/recharge',{customer_id:f.member.id,amount:100,gift_amount:20},f.from.id);await f.login(page);
 const profile=page.getByRole('dialog',{name:'会员详情：权益验收会员',exact:true});await profile.getByRole('button',{name:'调整权益',exact:true}).click();const form=page.getByRole('dialog',{name:'调整会员权益',exact:true});
 await form.getByLabel('本金调整',{exact:true}).fill('10');await form.getByRole('button',{name:'确认权益调整',exact:true}).click();await expect(form.getByRole('alert')).toContainText('请填写调整原因');
 await form.getByLabel('权益调整原因',{exact:true}).fill('核对权益');await f.api('/members/recharge',{customer_id:f.member.id,amount:50},f.to.id);
 const conflict=page.waitForResponse(r=>r.url().endsWith('/members/'+f.member.id+'/adjust'));await form.getByRole('button',{name:'确认权益调整',exact:true}).click();expect((await(await conflict).json()).code).toBe('ASSETS_CHANGED');await expect(form.getByLabel('本金调整',{exact:true})).toHaveValue('10');
 await form.getByRole('button',{name:'重新读取当前权益',exact:true}).click();await expect(form).toContainText('当前 150 → 调整后 160');await form.getByLabel('赠金调整',{exact:true}).fill('-5');await form.getByLabel('次数调整',{exact:true}).fill('2');await form.getByLabel('积分调整',{exact:true}).fill('8');
 const keys:string[]=[];let lose=true;await page.route('**/members/*/adjust',async route=>{keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();expect(response.ok()).toBe(true);if(lose){lose=false;await route.abort('failed')}else await route.fulfill({response})});
 await form.getByRole('button',{name:'确认权益调整',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click()});await expect(form.getByRole('button',{name:'核对原请求结果',exact:true})).toBeVisible();await expect(form.getByLabel('本金调整',{exact:true})).toBeDisabled();const replay=page.waitForResponse(r=>r.url().endsWith('/members/'+f.member.id+'/adjust'));await form.getByRole('button',{name:'核对原请求结果',exact:true}).click();expect((await(await replay).json()).ok).toBe(true);await expect(form).toBeHidden();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);await page.unrouteAll({behavior:'wait'});
 const state=await inTenant(f.merchantId,async()=>(await tenantQuery('SELECT balance,bonus_balance,times_balance,points FROM members WHERE id=$1',[f.member.id])).rows[0]);expect(state).toEqual({balance:160,bonus_balance:15,times_balance:2,points:8});expect(await inTenant(f.merchantId,async()=>(await tenantQuery("SELECT count(*)::int AS count FROM asset_operations WHERE member_id=$1 AND type='adjust'",[f.member.id])).rows[0].count)).toBe(1);
 const row=profile.getByRole('row').filter({hasText:'核对权益'});await row.getByRole('button',{name:'批次分配',exact:true}).click();await expect(page.getByRole('dialog',{name:'权益批次分配',exact:true})).toContainText('江畔店（验收）');await page.getByRole('button',{name:'关闭权益批次分配',exact:true}).click();await page.setViewportSize({width:1050,height:700});await profile.getByRole('button',{name:'调整权益',exact:true}).click();await expect(form.getByRole('button',{name:'确认权益调整',exact:true})).toBeInViewport();await page.screenshot({path:'.runtime/thera-member-adjustment.png',fullPage:true});expect(crashes).toEqual([]);
});
test('充值退款提交审批后资产不变，另一管理员批准，原申请人执行后准确冲回并保留原流水',async({page,request})=>{
 test.setTimeout(120000);const f=await fixture(request);const funded=await f.api('/members/recharge',{customer_id:f.member.id,amount:80,gift_amount:8,method:'现金'},f.from.id);
 const reviewer=await f.api('/users',{username:'refund-reviewer',password:f.password,name:'退款审核店长'});await f.api('/users/'+reviewer.id+'/grants',{grants:[{store_id:f.from.id,role:'manager'}]},undefined,'PUT');const signed=await f.api('/auth/login',{merchant_code:(await f.api('/session',undefined,f.from.id,'GET')).merchant.code,username:'refund-reviewer',password:f.password});
 await f.api('/settings',{approval_thresholds:JSON.stringify({refund:10,discount:0,inventory_adjustment:0})},f.from.id);await f.login(page);
 const profile=page.getByRole('dialog',{name:'会员详情：权益验收会员',exact:true});await profile.getByTestId('member-asset-'+funded.operation.id).getByRole('button',{name:'登记充值退款',exact:true}).click();const form=page.getByRole('dialog',{name:'登记充值退款',exact:true});await expect(form).toContainText('¥80.00');await form.getByLabel('充值退款原因',{exact:true}).fill('整笔充值退还');await form.getByRole('button',{name:'确认退款登记',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});await expect(form).toBeHidden();await expect(profile.getByRole('status')).toContainText('资产尚未改变');
 const account=await f.api('/members/'+f.member.id,undefined,f.from.id,'GET');expect(account.balance).toBe(80);expect(account.bonus_balance).toBe(8);const approvals=await f.api('/approvals?status=pending',undefined,f.from.id,'GET');expect(approvals).toHaveLength(1);await f.api('/approvals/'+approvals[0].id+'/review',{status:'approved'},f.from.id,'POST',signed.token);
 await page.getByRole('button',{name:'关闭会员详情：权益验收会员',exact:true}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/审批中心/}).click();const entry=page.getByRole('article').filter({hasText:'整笔充值退还'});await entry.getByRole('button',{name:'执行原操作',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});await expect(entry).toContainText('已执行');
 const after=await f.api('/members/'+f.member.id,undefined,f.from.id,'GET');expect(after.balance).toBe(0);expect(after.bonus_balance).toBe(0);expect(after.transactions).toHaveLength(2);expect(after.transactions.find((r:any)=>r.id===funded.operation.id).reversed_by).toBeTruthy();
 const money=await inTenant(f.merchantId,async()=>(await tenantQuery("SELECT amount,method FROM shift_entries WHERE kind='recharge_reversal' AND asset_operation_id IN(SELECT id FROM asset_operations WHERE member_id=$1)",[f.member.id])).rows);expect(money).toEqual([{amount:-80,method:'现金'}]);
});
