import {test,expect} from './fixtures.js';import {randomUUID} from 'node:crypto';import {platformPool} from '../../apps/server/src/db/pools.js';import {hashPassword} from '../../apps/server/src/security.js';
test('房态五色清晰区分，创建员工逐店勾选且真实接口隔离',async({page,request,browser})=>{
 const username='acl-ui-'+randomUUID(),password='Access-Test-873!',code='ACL-'+randomUUID().slice(0,8).toUpperCase();await platformPool.query('INSERT INTO platform_users(username,password,name) VALUES($1,$2,$3)',[username,await hashPassword(password),'权限验收']);
 const admin=(await(await request.post('/api/platform/v1/auth/login',{data:{username,password}})).json()).data;const created=(await(await request.post('/api/platform/v1/merchants',{headers:{Authorization:'Bearer '+admin.token},data:{code,name:'权限界面验收'}})).json()).data;await request.post('/api/merchant/v1/auth/activate',{data:{token:created.invite.token,username:'owner',password,name:'老板'}});
 const owner=(await(await request.post('/api/merchant/v1/auth/login',{data:{merchant_code:code,username:'owner',password}})).json()).data;
 const post=async(path:string,data:any,store?:number)=>{const r=await(await request.post('/api/merchant/v1'+path,{headers:{Authorization:'Bearer '+owner.token,'Idempotency-Key':randomUUID(),...(store?{'X-Store-ID':String(store)}:{})},data})).json();expect(r.ok,JSON.stringify(r)).toBe(true);return r.data};
 const store=await post('/stores',{code:'A',name:'授权一店'});await post('/stores',{code:'B',name:'授权二店'});
 for(const [i,status] of ['idle','occupied','cleaning','reserved','maintenance'].entries()){const room=await post('/rooms',{room_no:String(101+i)},store.id);if(status==='occupied')await post('/sessions',{resource_id:room.id},store.id);else if(status!=='idle')await post('/rooms/'+room.id+'/status',{status},store.id)}
 await page.goto('/');await page.getByLabel('商家编号',{exact:true}).fill(code);await page.getByLabel('账号',{exact:true}).fill('owner');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.locator('.board-room-card')).toHaveCount(5);
 const colors=await page.locator('.board-room-card').evaluateAll(els=>els.map(el=>getComputedStyle(el).backgroundColor));expect(new Set(colors).size).toBe(5);for(const status of ['空闲','使用中','待打扫','已预约','维修'])await expect(page.getByRole('button',{name:new RegExp('房间 .*，'+status)})).toBeVisible();await page.screenshot({path:'.runtime/board-status-colors.png'});
 await page.getByRole('button',{name:'商家管理',exact:true}).click();await page.getByLabel('员工账号',{exact:true}).fill('limited');await page.getByLabel('员工姓名',{exact:true}).fill('限定员工');await page.getByLabel('初始密码',{exact:true}).fill(password);await page.getByRole('button',{name:'创建员工',exact:true}).click();const modal=page.getByRole('dialog',{name:'限定员工的门店授权'});await expect(modal).toBeVisible();await modal.getByLabel('授权一店角色').selectOption('manager');await expect(modal.getByLabel('授权一店：会员管理',{exact:true})).not.toBeChecked();await modal.getByLabel('授权一店：房态与开房',{exact:true}).check();await modal.getByLabel('授权一店：会员管理',{exact:true}).check();await expect(modal.getByLabel('授权一店：会员充值',{exact:true})).not.toBeChecked();await modal.getByLabel('授权二店角色').selectOption('floor');await modal.getByLabel('授权二店：排队叫号',{exact:true}).check();await modal.getByRole('button',{name:'保存授权'}).click();await expect(modal).toBeHidden();
 await page.getByRole('row').filter({hasText:'限定员工'}).getByRole('button',{name:'编辑授权'}).click();await expect(modal.getByLabel('授权一店：会员管理',{exact:true})).toBeChecked();await expect(modal.getByLabel('授权一店：经营报表与工资',{exact:true})).not.toBeChecked();await expect(modal.getByLabel('授权二店：排队叫号',{exact:true})).toBeChecked();await modal.getByRole('button',{name:'取消',exact:true}).click();
 const ctx=await browser.newContext();try{const staff=await ctx.newPage();await staff.goto('http://127.0.0.1:5175/');await staff.getByLabel('商家编号',{exact:true}).fill(code);await staff.getByLabel('账号',{exact:true}).fill('limited');await staff.getByLabel('密码',{exact:true}).fill(password);await staff.getByRole('button',{name:'登录',exact:true}).click();await expect(staff.locator('.board-room-card')).toHaveCount(5);await expect(staff.getByRole('navigation',{name:'主导航'})).not.toContainText('报表中心');const result=await staff.evaluate(async()=>{const value=JSON.parse(sessionStorage.getItem('za-spa-saas:merchant-session:v1')!);return (await fetch('/api/merchant/v1/reports/daily',{headers:{Authorization:'Bearer '+value.token,'X-Store-ID':String(value.current_store_id)}})).status});expect(result).toBe(403)}finally{await ctx.close()}
});

