import {test,expect} from './fixtures.js';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {platformPool,inTenant,tenantQuery} from '../../apps/server/src/db/pools.js';
import {hashPassword} from '../../apps/server/src/security.js';
test('连锁模板真实创建、显式选店和预览防覆盖，会员配置下发后向指定会员发券',async({page,request})=>{
 test.setTimeout(120000);assert.equal(process.env.NODE_ENV,'test');assert.equal(new URL(process.env.DATABASE_URL!).pathname,'/za_spa_saas_test');
 const username='templates-'+randomUUID(),password='Templates-Test-987!',code='TPL-'+randomUUID().slice(0,8).toUpperCase();await platformPool.query('INSERT INTO platform_users(username,password,name) VALUES($1,$2,$3)',[username,await hashPassword(password),'模板验收管理员']);
 const login=await(await request.post('/api/platform/v1/auth/login',{data:{username,password}})).json(),created=await(await request.post('/api/platform/v1/merchants',{headers:{Authorization:'Bearer '+login.data.token},data:{code,name:'模板验收商家'}})).json();expect(created.ok).toBe(true);
 expect((await(await request.post('/api/merchant/v1/auth/activate',{data:{token:created.data.invite.token,username:'13800138000',password,name:'模板老板'}})).json()).ok).toBe(true);
 const auth=await(await request.post('/api/merchant/v1/auth/login',{data:{merchant_code:code,username:'13800138000',password}})).json();let storeId:number|undefined;
 async function api(path:string,data?:any,method='POST'){const result=await(await request.fetch('/api/merchant/v1'+path,{method,headers:{Authorization:'Bearer '+auth.data.token,'Idempotency-Key':randomUUID(),...(storeId?{'X-Store-ID':String(storeId)}:{})},data})).json();expect(result.ok,JSON.stringify(result)).toBe(true);return result.data}
 const store=await api('/stores',{code:'001',name:'一店'}),other=await api('/stores',{code:'002',name:'二店'});storeId=store.id;const member=await api('/members',{name:'领券会员'});
 let holdLists=false,releaseLists!:()=>void;const listsReleased=new Promise<void>(resolve=>{releaseLists=resolve});await page.route('**/catalog/templates?*',async route=>{if(holdLists)await listsReleased;await route.continue()});
 try{
 const crashes:string[]=[];page.on('pageerror',e=>crashes.push(e.message));await page.goto('/');await page.getByLabel('商家编号',{exact:true}).fill(code);await page.getByLabel('账号',{exact:true}).fill('13800138000');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/连锁模板/}).click();await page.getByRole('button',{name:'新建模板',exact:true}).click();const form=page.getByRole('dialog',{name:'新建商家模板'});await form.getByLabel('名称',{exact:true}).fill('连锁服务');await form.getByLabel('售价（元）',{exact:true}).fill('80');let response=page.waitForResponse(r=>r.url().endsWith('/catalog/templates')&&r.request().method()==='POST');await form.getByRole('button',{name:'保存模板',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});const saved=(await(await response).json()).data;const row=page.getByTestId('template-'+saved.id);await expect(row).toBeVisible();
 await row.getByRole('button',{name:'下发',exact:true}).click();let dialog=page.getByRole('dialog',{name:'选择门店并预览下发'});await expect(dialog.getByRole('button',{name:'确认下发',exact:true})).toBeDisabled();await dialog.getByLabel('一店',{exact:true}).check();await dialog.getByRole('button',{name:'预览差异',exact:true}).click();await expect(dialog).toContainText('一店 · 新增配置');response=page.waitForResponse(r=>r.url().endsWith('/catalog/distribute'));await dialog.getByRole('button',{name:'确认下发',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});expect((await(await response).json()).ok).toBe(true);await expect(dialog).toBeHidden();
 const counts=await inTenant(created.data.merchant.id,async()=>(await tenantQuery('SELECT store_id,count(*)::int AS count FROM items GROUP BY store_id')).rows);expect(counts).toEqual([{store_id:store.id,count:1}]);expect(counts.some((r:any)=>r.store_id===other.id)).toBe(false);
 await row.getByRole('button',{name:'下发记录',exact:true}).click();await expect(page.getByRole('dialog',{name:'模板下发记录'})).toContainText('一店');await page.getByRole('button',{name:'关闭模板下发记录'}).click();
 await row.getByRole('button',{name:'下发',exact:true}).click();dialog=page.getByRole('dialog',{name:'选择门店并预览下发'});await dialog.getByLabel('一店',{exact:true}).check();await dialog.getByRole('button',{name:'预览差异',exact:true}).click();await expect(dialog).toContainText('内容一致');
 const item=(await api('/items',undefined,'GET'))[0];await api('/items',{id:item.id,name:item.name,type:item.type,price:90,stock:item.stock,duration:item.duration});response=page.waitForResponse(r=>r.url().endsWith('/catalog/distribute'));await dialog.getByRole('button',{name:'确认下发',exact:true}).click();expect((await(await response).json()).code).toBe('PREVIEW_CHANGED');await expect(dialog.getByRole('alert')).toContainText('重新预览');await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'重新预览',exact:true}).click();await expect(dialog).toContainText('90 → 80');holdLists=true;await dialog.getByRole('button',{name:'确认下发',exact:true}).click();await expect(dialog).toBeHidden();
 await page.getByRole('button',{name:'优惠券配置',exact:true}).click();await page.getByRole('button',{name:'新建模板',exact:true}).click();const couponForm=page.getByRole('dialog',{name:'新建商家模板'});await couponForm.getByLabel('名称',{exact:true}).fill('连锁新客券');const couponSaved=page.waitForResponse(r=>r.url().endsWith('/catalog/templates')&&r.request().method()==='POST');await couponForm.getByRole('button',{name:'保存模板',exact:true}).click();expect((await(await couponSaved).json()).ok).toBe(true);holdLists=false;releaseLists();await expect(couponForm).toBeHidden();const couponRow=page.getByRole('row').filter({hasText:'连锁新客券'});await couponRow.getByRole('button',{name:'下发',exact:true}).click();dialog=page.getByRole('dialog',{name:'选择门店并预览下发'});await dialog.getByLabel('一店',{exact:true}).check();await dialog.getByRole('button',{name:'预览差异',exact:true}).click();await dialog.getByRole('button',{name:'确认下发',exact:true}).click();await expect(dialog).toBeHidden();
 expect(await inTenant(created.data.merchant.id,async()=>(await tenantQuery('SELECT count(*)::int AS count FROM coupons')).rows[0].count)).toBe(0);
 await page.screenshot({path:'.runtime/templates-ui.png',fullPage:true});
 await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:/会员/}).click();await page.getByRole('row').filter({hasText:'领券会员'}).getByRole('button',{name:'详情',exact:true}).click();await page.getByRole('button',{name:'+ 发券',exact:true}).click();const issue=page.getByRole('dialog',{name:'发券给：领券会员'});await issue.getByLabel('连锁优惠券配置').selectOption({label:'连锁新客券 · 10 元 · 30 天'});response=page.waitForResponse(r=>/\/coupon-profiles\/\d+\/issue$/.test(r.url()));await issue.getByRole('button',{name:'确认发券',exact:true}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});expect((await(await response).json()).ok).toBe(true);await expect(issue).toBeHidden();await expect(page.getByRole('row').filter({hasText:'连锁新客券'})).toContainText('未使用');
 const coupons=await inTenant(created.data.merchant.id,async()=>(await tenantQuery('SELECT member_id,value FROM coupons')).rows);expect(coupons).toEqual([{member_id:member.id,value:10}]);expect(crashes).toEqual([]);
 }finally{holdLists=false;releaseLists();await page.unrouteAll({behavior:'wait'})}
});
