import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {harness,succeeded} from './helpers.js';
let h:Awaited<ReturnType<typeof harness>>,a:any,b:any;
before(async()=>{h=await harness();a=await h.onboard();b=await h.onboard()});after(async()=>h.stop());
const api=(t:any,s:number,path:string,method='GET',body?:any,key?:string)=>h.api(t.token,t.stores[s].id,path,method,body,key);
const room=async(t:any,s:number=0)=>succeeded(await api(t,s,'/rooms','POST',{room_no:randomUUID().slice(0,8),room_name:'预约房间',room_type:'标准'}));
const reservation=(roomId:number)=>({customer_name:'预约客人',customer_phone:'13800138000',room_id:roomId,reserve_time:'2026-12-20 14:00',duration:60,people:2});
test('预约校验与资源冲突：同商家跨店及跨商家 ID 均拒绝，时区明确',async()=>{
 const ra=await room(a),other=await room(a,1),foreign=await room(b);
 for(const id of [other.id,foreign.id])assert.equal((await api(a,0,'/reservations','POST',reservation(id))).status,404);
 assert.equal((await api(a,0,'/reservations','POST',{...reservation(ra.id),reserve_time:'2026-02-30 14:00'})).status,400);
 assert.equal((await api(a,0,'/reservations','POST',{...reservation(ra.id),people:0})).status,400);
 const results=await Promise.all([api(a,0,'/reservations','POST',reservation(ra.id)),api(a,0,'/reservations','POST',reservation(ra.id))]);
 assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const saved=results.find(r=>r.status===200)!.data;
 assert.equal(saved.reserve_time,'2026-12-20T06:00:00.000Z');
 assert.equal(succeeded(await api(a,0,'/rooms')).find((r:any)=>r.id===ra.id).status,'reserved');
 succeeded(await api(a,0,'/reservations','POST',{...reservation(ra.id),reserve_time:'2026-12-20T15:00:00+08:00'}));
 assert.equal(succeeded(await api(b,0,'/reservations')).some((r:any)=>r.id===saved.id),false);
 assert.equal((await api(b,0,`/reservations/${saved.id}/status`,'POST',{version:1,status:'arrived'})).status,404);
});
test('预约到店重复点击只建一张真实订单，归档先取消且保留历史',async()=>{
 const ra=await room(a),saved=succeeded(await api(a,0,'/reservations','POST',reservation(ra.id)));
 const edited=succeeded(await api(a,0,'/reservations','POST',{...reservation(ra.id),id:saved.id,version:1,remark:'需要安静'}));assert.equal(edited.version,2);
 assert.equal((await api(a,0,`/reservations/${saved.id}/status`,'POST',{version:1,status:'arrived'})).status,409);
 const results=await Promise.all([api(a,0,`/reservations/${saved.id}/arrive-open`,'POST',{version:2}),api(a,0,`/reservations/${saved.id}/arrive-open`,'POST',{version:2})]);
 results.forEach(succeeded);assert.equal(results[0].data.id,results[1].data.id);assert.equal(results[0].data.order.customer_phone,'13800138000');
 assert.equal(succeeded(await api(a,0,'/orders')).filter((o:any)=>o.reservation_id===saved.id).length,1);
 assert.equal((await api(a,0,`/reservations/${saved.id}/status`,'POST',{version:3,status:'cancelled'})).status,409);
 const rb=await room(a),pending=succeeded(await api(a,0,'/reservations','POST',reservation(rb.id)));
 assert.equal((await api(a,0,`/reservations/${pending.id}`,'DELETE',{version:1})).status,409);
 const cancelled=succeeded(await api(a,0,`/reservations/${pending.id}/status`,'POST',{version:1,status:'cancelled'}));
 succeeded(await api(a,0,`/reservations/${pending.id}`,'DELETE',{version:cancelled.version}));
 assert.equal(succeeded(await api(a,0,'/rooms')).find((r:any)=>r.id===rb.id).status,'idle');
 assert.equal(succeeded(await api(a,0,'/reservations')).some((r:any)=>r.id===pending.id),false);
});
test('排号同店并发唯一，商家及门店可复用编号，状态不能倒退',async()=>{
 const key=randomUUID(),body={customer_name:'排队客人',people:2};
 const repeated=await Promise.all([api(a,0,'/queue/take','POST',body,key),api(a,0,'/queue/take','POST',body,key)]);repeated.forEach(succeeded);assert.equal(repeated[0].data.id,repeated[1].data.id);
 const a1=repeated[0].data,b1=succeeded(await api(b,0,'/queue/take','POST',body,key)),a2=succeeded(await api(a,1,'/queue/take','POST',body,key));assert.equal(a1.queue_no,b1.queue_no);assert.equal(a1.queue_no,a2.queue_no);
 const more=await Promise.all(Array.from({length:5},()=>api(a,0,'/queue/take','POST',body)));more.forEach(succeeded);assert.equal(new Set(more.map(r=>r.data.queue_no)).size,5);
 assert.equal((await api(b,0,`/queue/${a1.id}/call`,'POST',{version:1})).status,404);
 const called=succeeded(await api(a,0,`/queue/${a1.id}/call`,'POST',{version:1}));
 assert.equal((await api(a,0,`/queue/${a1.id}/done`,'POST',{version:1})).status,409);
 const done=succeeded(await api(a,0,`/queue/${a1.id}/done`,'POST',{version:called.version}));assert.equal((await api(a,0,`/queue/${a1.id}/call`,'POST',{version:done.version})).status,409);
 const summary=succeeded(await api(a,0,'/queue/summary'));assert.equal(summary.waiting_count,5);assert.equal(summary.waiting_people,10);
});
test('顾客入口只返回叫号摘要和持凭据的本人排号，停用和限流按门店隔离',async()=>{
 const path=(t:any)=>`/api/public/v1/${t.merchant.code}/${t.stores[0].code}/queue`;
 const body={customer_name:'扫码客人',people:3,phone:'13812345678'},key=randomUUID();
 const first=succeeded(await h.call(path(a)+'/take','POST',body,undefined,undefined,key));
 const replay=succeeded(await h.call(path(a)+'/take','POST',body,undefined,undefined,key));assert.equal(replay.id,first.id);assert.equal(replay.access_token,first.access_token);
 const own=succeeded(await h.call(path(a)+'/'+first.id,'GET',undefined,first.access_token));assert.equal(own.queue_no,first.queue_no);assert.equal(own.phone,undefined);
 assert.equal((await h.call(path(b)+'/'+first.id,'GET',undefined,first.access_token)).status,404);
 assert.equal((await h.call(path(a)+'/'+first.id,'GET',undefined,'x'.repeat(43))).status,404);
 const summary=succeeded(await h.call(path(a)));assert.equal(summary.store.name,a.stores[0].name);assert.equal(JSON.stringify(summary).includes('13812345678'),false);assert.equal(summary.queue,undefined);
 for(let i=0;i<9;i++)succeeded(await h.call(path(a)+'/take','POST',body,undefined,undefined,randomUUID()));
 assert.equal((await h.call(path(a)+'/take','POST',body,undefined,undefined,randomUUID())).status,429);succeeded(await h.call(path(b)+'/take','POST',body,undefined,undefined,randomUUID()));
 succeeded(await h.call(`/api/platform/v1/merchants/${a.merchant.id}/status`,'PATCH',{status:'suspended'},h.platformToken));
 assert.equal((await h.call(path(a)+'/take','POST',body,undefined,undefined,randomUUID())).status,403);succeeded(await h.call(path(a)+'/'+first.id,'GET',undefined,first.access_token));succeeded(await h.call(path(b)+'/take','POST',body,undefined,undefined,randomUUID()));
});
