import {useCallback,useState} from 'react'
import {api} from '../api'
import {remote} from '../api/transport'
import {useAuth,isPlatformSuperadmin} from '../store/auth'
import {can} from '../utils/permissions'
import {useAutoRefresh} from '../hooks/useAutoRefresh'
import {AsyncButton,EmptyState} from '../components/ui'
import {fmtDateTime,fmtMoney} from '../utils/format'
import {toast} from '../store/toast'
const labels:Record<string,string>={pending:'待审核',approved:'已批准，待执行',rejected:'已驳回',consumed:'已执行',cancelled:'已撤销'}
export default function Approvals(){
 const user=useAuth(s=>s.user)!,[rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[status,setStatus]=useState('all')
 const load=useCallback(async()=>{try{setRows(await api.listApprovals(status));setError('')}catch(e){setError(e instanceof Error?e.message:'审批加载失败')}},[status]);useAutoRefresh(load)
 async function review(id:number,status:'approved'|'rejected'){const result=await api.reviewApproval(id,status);if(!result.ok)throw Error(result.msg??'审核失败');await load()}
 async function execute(row:any){const request=JSON.parse(row.after_snapshot).execute;if(!request?.path?.startsWith('/')||request.path.startsWith('//')||!['POST','PUT'].includes(request.method))throw Error('审批操作信息无效');const result=await remote<any>('/api/merchant/v1'+request.path,{method:request.method,headers:{'Idempotency-Key':'approval-execute-'+row.id},body:JSON.stringify({...request.body,approval_id:row.id})});if(!result.ok)throw Error(result.msg??'执行失败');toast('已执行并记录业务流水');await load()}
 return <div className="h-full overflow-auto p-5 space-y-4"><header className="flex justify-between items-center"><h1 className="text-xl font-bold">审批中心</h1><select aria-label="审批状态" className="input max-w-48" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option>{Object.entries(labels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></header><p className="text-sm text-gray-500">{isPlatformSuperadmin()?'平台超级管理员可审核、执行或撤销本商家的审批。业务内容发生变化后仍需重新核对。':'由另一位获授权人员审核，原申请人执行。批准后 24 小时内有效；业务金额或库存改变后需重新申请。'}</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="space-y-3">{rows.map(row=>{const detail=JSON.parse(row.after_snapshot??'{}');return <article className="card p-4 space-y-3" key={row.id}><div className="flex justify-between"><strong>#{row.id} · {{refund:'退款 / 退单',discount:'优惠',inventory_adjustment:'库存调整'}[row.action_type as string]??row.action_type} · {fmtMoney(detail.requested_amount)}</strong><span>{labels[row.status]}</span></div><p className="text-sm">{row.reason}</p><p className="text-xs text-gray-500">{row.requester_name} · {fmtDateTime(row.requested_at)}{row.reviewer_name&&` · 审核：${row.reviewer_name}`}</p><details className="text-xs"><summary className="cursor-pointer">查看申请内容</summary><pre className="whitespace-pre-wrap bg-gray-50 p-3 mt-2">{JSON.stringify(detail.operation,null,2)}</pre></details><div className="flex gap-3">{row.status==='pending'&&(isPlatformSuperadmin()||row.requested_by!==user.id)&&can(user,'approve')&&<><AsyncButton className="btn-primary" onClick={()=>review(row.id,'approved')}>批准</AsyncButton><AsyncButton className="btn-secondary" onClick={()=>review(row.id,'rejected')}>驳回</AsyncButton></>}{row.status==='approved'&&(isPlatformSuperadmin()||row.requested_by===user.id)&&<AsyncButton className="btn-primary" onClick={()=>execute(row)}>执行原操作</AsyncButton>}{['pending','approved'].includes(row.status)&&(isPlatformSuperadmin()||row.requested_by===user.id)&&<AsyncButton className="btn-ghost" onClick={async()=>{const result=await remote<any>(`/api/merchant/v1/approvals/${row.id}/cancel`,{method:'POST',body:'{}'});if(!result.ok)throw Error(result.msg);await load()}}>撤销申请</AsyncButton>}</div></article>})}{!rows.length&&!error&&<EmptyState text="暂无审批记录"/>}</div></div>
}
