import {useCallback,useRef,useState} from 'react'
import {TemplateDefinition,type TemplateType,type MerchantTemplate,type TemplatePreview} from '@za-spa/contracts'
import {api} from '../api'
import {useAuth} from '../store/auth'
import {toast} from '../store/toast'
import {parseMoneyInput} from '../utils/format'
import {useAutoRefresh} from '../hooks/useAutoRefresh'
import {AsyncButton,Modal,Confirm,EmptyState} from '../components/ui'

const names:Record<TemplateType,string>={item:'项目与商品',member_level:'会员等级',recharge_plan:'充值方案',coupon:'优惠券配置'}
const labels:Record<string,string>={name:'名称',type:'类型',price:'售价（元）',duration:'服务时长（分钟）',commission:'参考提成（元）',cost:'参考成本（元）',unit:'单位',low_stock_threshold:'低库存提醒数量',min_consume:'累计消费门槛（元）',discount:'会员折扣率',sort_order:'排序',amount:'充值本金（元）',gift_amount:'赠送金额（元）',value:'券面值或折扣率',min_amount:'用券消费门槛（元）',valid_days:'领取后有效天数'}
const defaults:Record<TemplateType,Record<string,any>>={item:{name:'',type:'service',price:0,duration:60,commission:0,cost:0,unit:'份',low_stock_threshold:10},member_level:{name:'',min_consume:0,discount:1,sort_order:0},recharge_plan:{name:'',amount:100,gift_amount:0,sort_order:0},coupon:{name:'',type:'cash',value:10,min_amount:0,valid_days:30}}
const display=(key:string,value:unknown)=>key==='type'?({service:'服务',product:'商品',cash:'代金券',discount:'折扣券'}[String(value)]??String(value)):String(value??'—')

export default function Headquarters():JSX.Element{
 const merchant=useAuth(s=>s.merchant),[type,setType]=useState<TemplateType>('item'),[rows,setRows]=useState<MerchantTemplate[]>([]),[stores,setStores]=useState<any[]>([]),[error,setError]=useState('')
 const [edit,setEdit]=useState<{id?:number;version?:number;type:TemplateType;payload:Record<string,any>}|null>(null),[formError,setFormError]=useState('')
 const [target,setTarget]=useState<MerchantTemplate|null>(null),[selected,setSelected]=useState<number[]>([]),[plan,setPlan]=useState<TemplatePreview|null>(null),[distributionError,setDistributionError]=useState(''),[history,setHistory]=useState<any[]|null>(null),[archive,setArchive]=useState<MerchantTemplate|null>(null)
 const busy=useRef(false),loadSequence=useRef(0)
 const load=useCallback(async()=>{const sequence=++loadSequence.current;try{const [templates,allStores]=await Promise.all([api.listCatalogTemplates(type),api.listStores()]);if(sequence===loadSequence.current){setRows(templates);setStores(allStores);setError('')}}catch(e){if(sequence===loadSequence.current)setError(e instanceof Error?e.message:'加载失败')}},[type])
 useAutoRefresh(load)
 const save=async()=>{if(!edit||busy.current)return;const payload={...edit.payload};if(edit.type==='item'){const price=parseMoneyInput(payload.price);if(!Number.isFinite(price)||price<=0){toast('模板售价必须大于 0','error');return}payload.price=price}busy.current=true;setFormError('');try{const parsed=TemplateDefinition.safeParse({type:edit.type,payload});if(!parsed.success)throw Error(parsed.error.issues.map(i=>i.message).join('；'));const saved=await api.saveCatalogTemplate({...parsed.data,id:edit.id,version:edit.version});loadSequence.current++;setRows(previous=>[saved,...previous.filter(row=>row.id!==saved.id)]);setEdit(null);toast('模板已保存')}catch(e){setFormError(e instanceof Error?e.message:'保存失败')}finally{busy.current=false}}
 const preview=async()=>{if(!target||busy.current)return;busy.current=true;setDistributionError('');try{setPlan(await api.previewCatalog({template_id:target.id,version:target.version,store_ids:selected}))}catch(e){setPlan(null);setDistributionError(e instanceof Error?e.message:'预览失败')}finally{busy.current=false}}
 const distribute=async()=>{if(!plan||busy.current)return;busy.current=true;setDistributionError('');try{const result=await api.distributeCatalog({template_id:plan.template.id,version:plan.template.version,store_ids:plan.targets.map(s=>s.store_id),preview_hash:plan.preview_hash});toast(`已核对 ${result.stores} 家门店，新增或更新 ${result.distributed} 项配置`);setTarget(null);setPlan(null)}catch(e){setDistributionError(e instanceof Error?e.message:'下发失败')}finally{busy.current=false}}
 return <div className="h-full flex flex-col"><header className="h-14 bg-white border-b flex items-center justify-between px-5"><h2 className="text-lg font-bold">连锁模板</h2><button className="btn-primary" onClick={()=>{setEdit({type,payload:{...defaults[type]}});setFormError('')}}>新建模板</button></header>
  <div className="px-5 py-3 bg-blue-50 text-sm text-blue-900">{merchant?.name} 的专属配置。下发前选择门店并核对差异；会员等级和充值方案用于门店开卡、充值，优惠券配置用于向指定会员发券。</div>
  <div className="flex gap-2 px-5 py-3">{Object.entries(names).map(([key,label])=><button key={key} className={type===key?'btn-primary':'btn-secondary'} onClick={()=>{setType(key as TemplateType);setRows([])}}>{label}</button>)}</div>
  {error&&<div role="alert" className="mx-5 p-3 bg-red-50 text-red-700">{error}<AsyncButton className="ml-3 underline" onClick={load}>重试加载</AsyncButton></div>}
  <div className="flex-1 overflow-auto px-5 pb-5">{!rows.length?<EmptyState text="暂无商家模板"/>:<table className="table w-full bg-white"><thead><tr><th>模板名称</th><th>配置内容</th><th>版本</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} data-testid={'template-'+row.id}><td>{row.name}</td><td className="max-w-xl"><div className="flex flex-wrap gap-x-3 gap-y-1 text-xs text-gray-600">{Object.entries(row.payload).filter(([k])=>k!=='name').map(([key,value])=><span key={key}>{labels[key]}：{display(key,value)}</span>)}</div></td><td>{row.version}</td><td>{row.active?'可用':'已停用'}</td><td><div className="flex gap-3">{row.active&&<><button className="text-brand-600" onClick={()=>{setEdit({id:row.id,version:row.version,type:row.type,payload:{...row.payload}});setFormError('')}}>编辑</button><button className="text-brand-600" onClick={()=>{setTarget(row);setSelected([]);setPlan(null);setDistributionError('')}}>下发</button><button className="text-red-600" onClick={()=>setArchive(row)}>停用</button></>}<AsyncButton className="text-gray-600" onClick={async()=>setHistory(await api.listCatalogDistribution(row.id))}>下发记录</AsyncButton></div></td></tr>)}</tbody></table>}</div>
  <Modal open={!!edit} title={edit?.id?'编辑商家模板':'新建商家模板'} onClose={()=>{if(!busy.current)setEdit(null)}} footer={<AsyncButton className="btn-primary" onClick={save}>保存模板</AsyncButton>}>
   {edit&&<div className="grid grid-cols-2 gap-4">{Object.entries(edit.payload).map(([key,value])=><label className="block" key={key}><span className="label">{labels[key]}</span>{key==='type'?<select className="input" value={value} onChange={e=>setEdit({...edit,payload:{...edit.payload,type:e.target.value}})}>{(edit.type==='item'?[['service','服务'],['product','商品']]:[['cash','代金券'],['discount','折扣券']]).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input className="input" type={key==='price'||typeof value==='number'?'number':'text'} step={['price','commission','cost','min_consume','discount','amount','gift_amount','value','min_amount'].includes(key)?'0.01':'1'} min={0} value={value} onChange={e=>setEdit({...edit,payload:{...edit.payload,[key]:key==='price'?e.target.value:(typeof value==='number'?Number(e.target.value):e.target.value)}})}/>}</label>)}</div>}
   {edit?.type==='item'&&<p className="mt-3 text-xs text-gray-500">首次下发的商品库存为 0，请通过入库录入实际数量；以后下发保留门店库存。同名的门店自建项目会保留，模板另建项目。</p>}
   {(edit?.type==='member_level'||edit?.type==='coupon')&&<p className="mt-3 text-xs text-gray-500">折扣率填写 0 到 1 之间的小数，例如 0.88 表示 8.8 折。</p>}
   {formError&&<p role="alert" className="mt-3 text-red-600">{formError}</p>}
  </Modal>
  <Modal open={!!target} title="选择门店并预览下发" width="max-w-3xl" onClose={()=>{if(!busy.current)setTarget(null)}} footer={<><AsyncButton className="btn-secondary" disabled={!selected.length} onClick={preview}>{plan?'重新预览':'预览差异'}</AsyncButton><AsyncButton className="btn-primary" disabled={!plan} onClick={distribute}>确认下发</AsyncButton></>}>
   <p className="mb-3 font-semibold">{target?.name} · 版本 {target?.version}</p><div className="flex flex-wrap gap-4">{stores.filter(s=>s.status===1).map(store=><label key={store.id} className="flex items-center gap-2"><input type="checkbox" checked={selected.includes(store.id)} onChange={e=>{if(busy.current)return;setSelected(e.target.checked?[...selected,store.id]:selected.filter(id=>id!==store.id));setPlan(null)}}/>{store.name}</label>)}</div>
   {plan&&<div className="mt-4 space-y-3">{plan.targets.map(store=><section key={store.store_id} className="p-3 rounded border"><h4 className="font-bold">{store.store_name} · {{create:'新增配置',update:'更新已有下发配置',unchanged:'内容一致'}[store.action]}</h4><dl className="grid grid-cols-2 gap-2 mt-2 text-xs">{Object.entries(store.after).map(([key,value])=><div key={key}><dt className="text-gray-500">{labels[key]}</dt><dd>{store.before?display(key,store.before[key])+' → ':''}{display(key,value)}</dd></div>)}</dl></section>)}</div>}
   {distributionError&&<p role="alert" className="mt-3 text-red-600">{distributionError}</p>}
  </Modal>
  <Modal open={history!==null} title="模板下发记录" onClose={()=>setHistory(null)}>{history?.length?<table className="table w-full"><thead><tr><th>门店</th><th>下发版本</th><th>最后下发时间</th></tr></thead><tbody>{history.map(row=><tr key={row.store_id}><td>{row.store_name}</td><td>{row.template_version}</td><td>{new Date(row.applied_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</td></tr>)}</tbody></table>:<EmptyState text="尚未向门店下发"/>}</Modal>
  <Confirm open={!!archive} title="停用模板" message={`停用“${archive?.name??''}”后，已下发的门店配置继续保留。`} onCancel={()=>setArchive(null)} onConfirm={async()=>{if(!archive)return;await api.deleteCatalogTemplate(archive.id,archive.version,'老板停用连锁模板');setArchive(null);await load()}}/>
 </div>
}
