import PasswordInput from '../components/PasswordInput'
import {useCallback,useRef,useState} from 'react'
import {remote,isRemoteFailure} from '../api/transport'
import {useAuth,isPlatformSuperadmin} from '../store/auth'
import {api} from '../api'
import {useAutoRefresh} from '../hooks/useAutoRefresh'
import {toast} from '../store/toast'
import {AsyncButton,Confirm,Modal} from '../components/ui'
import StoreGrantEditor from '../components/StoreGrantEditor'
import {exportBusiness} from '../api/export'
const P='/api/merchant/v1'
export default function OwnerConsole(){
 const stores=useAuth(s=>s.stores),merchant=useAuth(s=>s.merchant),[users,setUsers]=useState<any[]>([]),[operators,setOperators]=useState<any[]>([]),[grants,setGrants]=useState<any[]>([]),[error,setError]=useState('')
 const [storeForm,setStoreForm]=useState<{code:string;name:string;point_clock_business_type:'BATH'|'FOOT'|null}>({code:'',name:'',point_clock_business_type:null}),[userForm,setUserForm]=useState({username:'',name:'',password:''}),[selected,setSelected]=useState<any>(null),[assignment,setAssignment]=useState<Record<number,{role:string;technician_id?:number}>>({})
 const storeTypeLock=useRef(false),[savingStoreType,setSavingStoreType]=useState<number|null>(null)
 const [accountTarget,setAccountTarget]=useState<any>(null),[accountForm,setAccountForm]=useState({name:'',active:1,password:''})
 const [storeAction,setStoreAction]=useState<{store:any;kind:'status'|'delete'}|null>(null)
 const load=useCallback(()=>{return Promise.all([remote<any[]>(P+'/users'),remote<any>(P+'/support/operators'),remote<any>(P+'/support/grants')]).then(([u,o,g])=>{setUsers(u);setOperators(o.items);setGrants(g.items);setError('')}).catch(e=>setError(e.message))},[]);useAutoRefresh(load,60000)
 async function save(path:string,body:any,method='POST'){const result=await remote<any>(P+path,{method,body:JSON.stringify(body)});if(isRemoteFailure(result))throw Error(result.msg);await load();return result}
 return <div className="p-6 overflow-auto h-full space-y-6"><header><h1 className="text-2xl font-semibold">商家管理</h1><p className="text-sm text-gray-500 mt-1">{merchant?.name} · {merchant?.code} · {merchant?.member_mode==='merchant'?'会员商家通用':'会员单店独立'}</p></header>{error&&<p role="alert" className="text-red-600">{error}</p>}
 <section className="card p-5"><h2 className="font-semibold mb-4">门店</h2><div className="grid md:grid-cols-3 gap-3">{stores.map(store=><div className="border rounded-lg p-4" key={store.id}><div className="font-medium">{store.name}</div><div className="text-xs text-gray-500 mt-1">{store.code} · {store.status===1?'营业中':'已停用'}</div><label className="block text-xs text-gray-500 mt-3">点钟王门店业态<select aria-label={`${store.name}点钟王门店业态`} className="input mt-1" value={store.point_clock_business_type??''} disabled={savingStoreType!==null} onChange={async e=>{if(storeTypeLock.current)return;const point_clock_business_type=e.target.value as 'BATH'|'FOOT';storeTypeLock.current=true;setSavingStoreType(store.id);setError('');try{await save('/stores/'+store.id,{name:store.name,point_clock_business_type},'PUT');await api.refreshSession();toast('点钟王门店业态已保存')}catch(e){const message=e instanceof Error?e.message:'门店业态保存失败，请重试';setError(message);toast(message,'error')}finally{storeTypeLock.current=false;setSavingStoreType(null)}}}><option value="" disabled>尚未配置</option><option value="BATH">洗浴</option><option value="FOOT">足浴</option></select></label><div className="flex gap-2 mt-2"><button className="btn-ghost text-xs" onClick={()=>setStoreAction({store,kind:'status'})}>{store.status===1?'停用门店':'启用门店'}</button><button className="btn-ghost text-xs text-red-600" disabled={store.status===1} title={store.status===1?'请先停用门店':'仅可删除没有关联记录的空门店'} onClick={()=>setStoreAction({store,kind:'delete'})}>删除门店</button></div></div>)}</div><div className="flex flex-wrap gap-3 mt-4"><input aria-label="门店编号" className="input max-w-36" placeholder="门店编号" value={storeForm.code} onChange={e=>setStoreForm({...storeForm,code:e.target.value})}/><input aria-label="门店名称" className="input max-w-64" placeholder="门店名称" value={storeForm.name} onChange={e=>setStoreForm({...storeForm,name:e.target.value})}/><select aria-label="点钟王门店业态" className="input max-w-40" value={storeForm.point_clock_business_type??''} onChange={e=>setStoreForm({...storeForm,point_clock_business_type:(e.target.value||null) as 'BATH'|'FOOT'|null})}><option value="">暂不配置点钟王</option><option value="BATH">洗浴</option><option value="FOOT">足浴</option></select><AsyncButton className="btn-primary" onClick={async()=>{await save('/stores',storeForm);setStoreForm({code:'',name:'',point_clock_business_type:null});await api.refreshSession()}}>新增门店</AsyncButton></div></section>
 <section className="card p-5"><h2 className="font-semibold mb-4">员工与门店授权</h2><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left text-gray-500"><th className="p-2">姓名 / 账号</th><th>身份</th><th>门店授权</th><th>操作</th></tr></thead><tbody>{users.map(user=><tr className="border-t" key={user.id}><td className="p-3">{user.name}<div className="text-xs text-gray-400">{user.username}</div></td><td>{user.role==='owner'?(user.active===1?'商家老板':'商家老板 · 已停用'):user.active===1?'员工':'已停用'}</td><td>{user.role==='owner'?'本商家全部门店':user.store_grants.map((g:any)=>`${stores.find(s=>s.id===g.store_id)?.name??g.store_id} (${g.role})`).join('、')||'未授权'}</td><td>{isPlatformSuperadmin()&&<button className="btn-ghost" onClick={()=>{setAccountTarget(user);setAccountForm({name:user.name,active:user.active,password:''})}}>维护账号</button>}{user.role!=='owner'&&<><button className="btn-ghost" onClick={()=>{setSelected(user);setAssignment(Object.fromEntries(user.store_grants.map((g:any)=>[g.store_id,{role:g.role,technician_id:g.technician_id}])));}}>编辑授权</button><AsyncButton className="btn-ghost" onClick={()=>save('/users/'+user.id,{active:user.active===1?0:1},'PATCH')}>{user.active===1?'停用':'启用'}</AsyncButton></>}</td></tr>)}</tbody></table></div><div className="grid sm:grid-cols-4 gap-3 mt-4">{(['username','name','password'] as const).map(key=><PasswordInput key={key} aria-label={{username:'员工账号',name:'员工姓名',password:'初始密码'}[key]} className="input" type={key==='password'?'password':'text'} placeholder={{username:'员工账号',name:'员工姓名',password:'初始密码（8–20位字符）'}[key]} value={userForm[key]} onChange={e=>setUserForm({...userForm,[key]:e.target.value})}/>)}<AsyncButton className="btn-primary" onClick={async()=>{const created=await save('/users',userForm);setSelected({...created,store_grants:[]});setUserForm({username:'',name:'',password:''})}}>创建员工</AsyncButton></div></section>
 <section className="card p-5"><h2 className="font-semibold mb-2">平台协助</h2><p className="text-sm text-gray-500 mb-2">平台超级管理员拥有独立管理权限，不依赖此处的临时支持授权。</p><p className="text-sm text-gray-500 mb-4">支持访问默认只读，最长一小时，可随时撤销。完整维护授权允许调整业务资产及执行系统提供的删除、恢复操作，请仅授权可信平台人员。</p><div className="space-y-2">{(useAuth.getState().realm==='merchant'?operators:[]).map(operator=><div className="flex items-center gap-3" key={operator.id}><span className="min-w-36">{operator.name}</span><AsyncButton className="btn-secondary" onClick={()=>save('/support/grants',{platform_user_id:operator.id,scope:'read',duration_minutes:30})}>授权只读 30 分钟</AsyncButton><AsyncButton className="btn-ghost" onClick={()=>save('/support/grants',{platform_user_id:operator.id,scope:'configuration',duration_minutes:30})}>授权配置维护</AsyncButton><AsyncButton className="btn-ghost text-red-700" onClick={()=>save('/support/grants',{platform_user_id:operator.id,scope:'maintenance',duration_minutes:30})}>授权完整维护 30 分钟</AsyncButton></div>)}</div><div className="mt-4 space-y-2">{grants.filter(g=>!g.revoked_at&&new Date(g.expires_at)>new Date()).map(grant=><div className="border rounded p-3 flex justify-between text-sm" key={grant.id}><span>{grant.scope==='maintenance'?'完整维护':grant.scope==='read'?'只读支持':'配置维护'} · 截止 {new Date(grant.expires_at).toLocaleTimeString()}</span>{useAuth.getState().realm==='merchant'&&<AsyncButton className="text-red-600" onClick={()=>save('/support/grants/'+grant.id,undefined,'DELETE')}>撤销授权</AsyncButton>}</div>)}</div></section>
 <section className="card p-5"><h2 className="font-semibold mb-2">经营数据归档</h2><p className="text-sm text-gray-500 mb-4">导出本商家各店的会员、订单、资金流水和库存等经营记录。商家停用后仍可由老板导出。</p><AsyncButton className="btn-secondary" onClick={async()=>{const count=await exportBusiness();toast(`已导出 ${count} 条经营记录`)}}>导出全部经营数据</AsyncButton></section>
 <Modal open={!!accountTarget} title="平台维护账号" onClose={()=>setAccountTarget(null)}><div className="space-y-4"><p>{accountTarget?.username}</p><label className="block">姓名<input className="input" value={accountForm.name} onChange={e=>setAccountForm({...accountForm,name:e.target.value})}/></label><label className="block">账号状态<select className="input" value={accountForm.active} onChange={e=>setAccountForm({...accountForm,active:Number(e.target.value)})}><option value={1}>启用</option><option value={0}>停用</option></select></label><label className="block">重置密码（留空保留原密码）<PasswordInput className="input" value={accountForm.password} autoComplete="new-password" onChange={e=>setAccountForm({...accountForm,password:e.target.value})}/></label><AsyncButton className="btn-primary" onClick={async()=>{await save('/users/'+accountTarget.id,{name:accountForm.name,active:accountForm.active,...(accountForm.password?{password:accountForm.password}:{})},'PATCH');setAccountTarget(null);setAccountForm({name:'',active:1,password:''});toast('账号已更新，原有登录会话已撤销')}}>保存账号变更</AsyncButton></div></Modal>
 <Confirm open={!!storeAction} title={storeAction?.kind==='delete'?'删除空门店':storeAction?.store.status===1?'停用门店':'启用门店'} message={storeAction?.kind==='delete'?`确认删除 ${storeAction.store.name}？有关联记录的门店会被拒绝删除。`:`确认${storeAction?.store.status===1?'停用':'启用'} ${storeAction?.store.name??''}？停用后不能进行新营业，历史数据保留。`} danger={storeAction?.kind==='delete'} onCancel={()=>setStoreAction(null)} onConfirm={async()=>{if(!storeAction)return;const {store,kind}=storeAction;if(kind==='delete')await save('/stores/'+store.id,undefined,'DELETE');else await save('/stores/'+store.id,{name:store.name,status:store.status===1?0:1},'PUT');setStoreAction(null);await api.refreshSession(true);toast(kind==='delete'?'空门店已删除':store.status===1?'门店已停用':'门店已启用')}}/>
 {selected&&<StoreGrantEditor user={selected} stores={stores} onSaved={async grants=>{await load();setUsers(rows=>rows.map(row=>row.id===selected.id?{...row,store_grants:grants}:row));toast('授权已更新')}} onClose={()=>setSelected(null)}/>}
 </div>
}


