import PlatformRecovery from '../components/PlatformRecovery'
import {usePageTab} from '../hooks/usePageTab'
import PlatformStores from '../components/PlatformStores'
import {platformPreference,rememberPlatform} from '../utils/login-preferences'
import PasswordInput from '../components/PasswordInput'
import BrandMark from '../components/BrandMark'
import Icon,{type IconName} from '../components/Icon'
import {BRAND_NAME} from '../../../shared/brand'
import {useCallback,useEffect,useRef,useState} from 'react'
import {getServerUrl} from '../api/transport'
import {useAuth} from '../store/auth'
import {AsyncButton,Modal} from '../components/ui'
import './platform-console.css'
import './login.css'
const KEY='za-spa-saas:platform-session:v1',P='/api/platform/v1'
const sections=[['overview','平台总览','headquarters'],['merchants','商家管理','organization'],['support','支持授权','approvals'],['audit','审计中心','reports'],['operations','运行与备份','settings'],['security','账号安全','lock']] as const
const date=(v?:string)=>v?new Date(v).toLocaleString('zh-CN'):'—'
const activation=(v:string)=>({pending:'待激活',activated:'已激活',expired:'已过期'}[v]??'无邀请')
const actionName=(v:string)=>({'platform.superadmin.started':'进入商家超级管理','platform.superadmin.access':'平台超级管理操作','approval.platform_override':'平台直接执行经营操作','recovery.requested':'提交备份恢复任务','merchant.restored':'从备份恢复商家业务','store.disable':'停用门店','store.restore':'恢复门店','store.delete':'永久删除门店','platform.login':'平台登录','merchant.created':'开通商家','merchant.status':'变更商家状态','merchant.profile.updated':'修改商家资料','owner.invite.reissued':'补发老板邀请','owner.invite.revoked':'撤销老板邀请','platform.session.revoked':'撤销平台会话','platform.password.changed':'修改平台密码','platform.credentials.changed':'更新平台账号','support.revoked.by.operator':'结束支持授权'}[v]??v)
function Empty({children}:{children:React.ReactNode}){return <div className="pc-empty">{children}</div>}
function Badge({good,children}:{good?:boolean;children:React.ReactNode}){return <span className={'pc-badge '+(good?'is-good':'is-neutral')}>{children}</span>}
export default function PlatformConsole(){
 const [token,setToken]=useState(()=>sessionStorage.getItem(KEY)||''),[user,setUser]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),running=useRef(false)
 const [storeMerchant,setStoreMerchant]=useState<any>(null)
 const [recoveryMerchant,setRecoveryMerchant]=useState<any>(null)
 const [view,setView]=usePageTab<string>('overview',sections.map(s=>s[0])),[loading,setLoading]=useState(false),[updated,setUpdated]=useState('')
 const [remember,setRemember]=useState(()=>platformPreference().enabled)
 const [credentials,setCredentials]=useState(()=>({username:platformPreference().username,password:''})),[directory,setDirectory]=useState<any>({items:[],total:0}),[grants,setGrants]=useState<any[]>([]),[activity,setActivity]=useState<any>({items:[],total:0}),[sessions,setSessions]=useState<any[]>([])
 const [overview,setOverview]=useState<any>(null),[operations,setOperations]=useState<any>(null),[inviteMerchant,setInviteMerchant]=useState<any>(null),[inviteState,setInviteState]=useState<any>(null)
 const [form,setForm]=useState({code:'',name:'',member_mode:'store'}),[invite,setInvite]=useState<any>(null),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[activated,setActivated]=useState('all'),[page,setPage]=useState(1)
 const [auditSearch,setAuditSearch]=useState(''),[auditQuery,setAuditQuery]=useState(''),[auditPage,setAuditPage]=useState(1),[from,setFrom]=useState(''),[to,setTo]=useState(''),[auditFilter,setAuditFilter]=useState({from:'',to:''})
 const [editing,setEditing]=useState<any>(null),[name,setName]=useState(''),[reason,setReason]=useState(''),[statusTarget,setStatusTarget]=useState<any>(null),[detail,setDetail]=useState<any>(null)
 const [password,setPassword]=useState({current:'',next:'',confirm:''})
 const tokenRef=useRef(token);tokenRef.current=token;const generation=useRef(0),controllers=useRef(new Set<AbortController>())
 const clear=useCallback(()=>{for(const c of controllers.current)c.abort();generation.current++;tokenRef.current='';sessionStorage.removeItem(KEY);setToken('');setUser(null);setDirectory({items:[],total:0});setGrants([]);setActivity({items:[],total:0});setSessions([]);setInvite(null);setInviteMerchant(null);setInviteState(null);setOverview(null);setOperations(null);setPassword({current:'',next:'',confirm:''});setDetail(null);setStoreMerchant(null);setRecoveryMerchant(null);setEditing(null);setStatusTarget(null)},[])
 const request=useCallback(async(path:string,method='GET',body?:unknown)=>{
  const controller=new AbortController();controllers.current.add(controller);const timer=setTimeout(()=>controller.abort(),20000)
  try{const response=await fetch(getServerUrl()+P+path,{method,signal:controller.signal,credentials:'omit',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});
   const result=await response.json();if(tokenRef.current!==token)throw new DOMException('会话已切换','AbortError');if(!response.ok||result.ok!==true){if(response.status===401&&token)clear();throw Error(result.message??'请求失败')}return result.data
  }catch(e){if(controller.signal.aborted&&tokenRef.current===token)throw Error(method==='GET'?'读取超时，请刷新重试':'操作结果尚未确认，请刷新核对；邀请链接丢失可重新补发');throw e}finally{clearTimeout(timer);controllers.current.delete(controller)}
 },[token,clear])
 const load=useCallback(async()=>{
  const sequence=++generation.current;setLoading(true);setError('')
  try{
   const paths=view==='overview'?['/overview','/operations']:view==='merchants'?['/directory?'+new URLSearchParams({search:query,status,activation:activated,page:String(page)})]:view==='support'?['/support-grants']:view==='audit'?['/activity?'+new URLSearchParams({search:auditQuery,page:String(auditPage),...(auditFilter.from?{from:new Date(auditFilter.from+'T00:00:00+08:00').toISOString()}:{}),...(auditFilter.to?{to:new Date(new Date(auditFilter.to+'T00:00:00+08:00').getTime()+86400000).toISOString()}: {})})]:view==='operations'?['/operations']:['/sessions']
   const [session,...data]=await Promise.all([request('/session'),...paths.map(path=>request(path))]);if(sequence!==generation.current)return
   setUser(session.user);if(view==='overview'){setOverview(data[0]);setOperations(data[1])}else if(view==='merchants')setDirectory(data[0]);else if(view==='support')setGrants(data[0].items);else if(view==='audit')setActivity(data[0]);else if(view==='operations')setOperations(data[0]);else setSessions(data[0].items);setUpdated(new Date().toISOString())
  }catch(e){if(sequence===generation.current)setError(e instanceof Error?e.message:'连接失败')}finally{if(sequence===generation.current)setLoading(false)}
 },[request,view,query,status,activated,page,auditQuery,auditPage,auditFilter])
 useEffect(()=>{if(token)void load();return()=>{generation.current++}},[token,load])
 useEffect(()=>()=>{for(const c of controllers.current)c.abort()},[])
 async function login(event:React.FormEvent){event.preventDefault();if(running.current)return;running.current=true;setBusy(true);setError('');try{const result=await request('/auth/login','POST',credentials);if(result.realm!=='platform')throw Error('登录身份错误');rememberPlatform(remember,credentials.username);sessionStorage.setItem(KEY,result.token);setToken(result.token);setView('overview');setCredentials({username:remember?credentials.username:'',password:''})}catch(e){setError(e instanceof Error?e.message:'登录失败')}finally{running.current=false;setBusy(false)}}
 const createForm=<section className="pc-panel"><div className="pc-section-title"><div><h2>开通商家</h2><p>建立独立经营空间，让老板自行激活账号。</p></div><Icon name="plus"/></div><div className="pc-form-grid"><label>商家编号<input className="input" aria-label="商家编号" placeholder="如 THERA001" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label>商家名称<input className="input" aria-label="商家名称" placeholder="输入商家名称" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>会员模式<select className="input" aria-label="会员模式" value={form.member_mode} onChange={e=>setForm({...form,member_mode:e.target.value})}><option value="store">会员单店独立</option><option value="merchant">会员商家通用</option></select></label></div><div className="pc-form-footer"><p>首次产生会员或订单后锁定会员模式，邀请有效期为 7 天。</p><AsyncButton className="btn-primary" onClick={async()=>{const result=await request('/merchants','POST',form);setInvite(result.invite);setForm({code:'',name:'',member_mode:'store'});await load()}}>开通并生成老板邀请</AsyncButton></div>{invite&&<div className="pc-notice"><strong>老板邀请已生成</strong><p>有效期至 {date(invite.expires_at)}，请单独交给商家老板。</p><input className="input" aria-label="老板邀请链接" readOnly value={invite.activation_url}/><AsyncButton className="btn-secondary" onClick={()=>navigator.clipboard.writeText(invite.activation_url)}>复制邀请链接</AsyncButton></div>}</section>
 const health=<div className="pc-health-grid">{[['数据库',operations?.database==='healthy','业务数据库连接'],['后台任务',operations?.jobs?.healthy===true,'任务调度与最近运行'],['每日备份',operations?.backup?.status==='healthy','备份时效与磁盘监测']].map(([title,ok,description])=><div key={String(title)}><span className={'pc-dot '+(ok?'is-good':'is-warn')}/><h3>{title}</h3><p>{description}</p><Badge good={!!ok}>{!operations?'读取中':ok?'正常':'需要检查'}</Badge></div>)}</div>
 if(!token)return <div className="pc-login"><div className="pc-login-story"><BrandMark/><p>ZA THERA / PLATFORM</p><h1>让每一种规模，<br/>都有清晰的秩序。</h1><span>澜序 · 平台运营控制台</span></div><div className="pc-login-main"><nav className="login-mode-switch pc-login-switch" aria-label="登录入口"><a href="/">商家登录</a><span aria-current="page">平台登录</span></nav><form className="pc-login-form" onSubmit={login}><BrandMark/><h2>平台管理</h2><p>使用独立的平台管理员账号登录。</p>{error&&<p role="alert" className="pc-error">{error}</p>}<label>平台账号<input className="input" required autoComplete="username" value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})}/></label><label>密码<PasswordInput className="input" type="password" required autoComplete="current-password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/></label><label className="pc-remember-account"><input type="checkbox" checked={remember} onChange={e=>{setRemember(e.target.checked);if(!e.target.checked)rememberPlatform(false,'')}}/><span>记住账号（不保存密码）</span></label><button className="btn-primary" disabled={busy}>{busy?'正在登录…':'登录平台'}</button><a href="/">返回商家登录 →</a></form></div></div>
 return <div className="pc-shell"><aside className="pc-sidebar"><div className="pc-brand"><BrandMark/><div><strong>{BRAND_NAME}</strong><span>PLATFORM CONSOLE</span></div></div><p className="pc-nav-caption">运营工作区</p><nav aria-label="平台导航">{sections.map(([key,label,icon])=><button key={key} className={view===key?'active':''} aria-current={view===key?'page':undefined} onClick={()=>setView(key)}><Icon name={icon as IconName}/>{label}{view===key&&<span className="pc-nav-dot"/>}</button>)}</nav><div className="pc-sidebar-bottom"><span className="pc-dot is-good"/>独立商家 · 分层授权<p>洗浴娱乐行业智慧运营系统</p></div></aside><main className="pc-main"><header className="pc-header"><div><p>工作区 / {sections.find(s=>s[0]===view)?.[1]}</p><span>最近读取 {date(updated)}</span></div><div><span className="pc-avatar">{user?.name?.slice(0,1)??'管'}</span><strong>{user?.name??'正在读取'}</strong><AsyncButton className="btn-ghost" onClick={async()=>{await request('/auth/logout','POST');clear()}}>退出平台</AsyncButton></div></header><div className="pc-content"><div className="pc-page-title"><div><p>ZA THERA CONTROL CENTER</p><h1>{sections.find(s=>s[0]===view)?.[1]}</h1></div><AsyncButton className="btn-secondary" onClick={load} disabled={loading}><Icon name="refresh" size={16}/>{loading?'正在读取…':'刷新数据'}</AsyncButton></div>{error&&<div role="alert" className="pc-error">{error}</div>}
 {view==='overview'&&<><section className="pc-hero"><div><p>让门店，自成秩序。</p><h2>经营各有边界，<br/>管理尽在眼前。</h2><span>从商家开通到运行保障，掌握平台的每一个关键环节。</span></div><div className="pc-hero-stat"><span>已开通商家</span><strong>{overview?.merchants.total??'—'}</strong><button onClick={()=>setView('merchants')}>查看商家管理 <Icon name="arrow"/></button></div></section><div className="pc-metrics">{[['正常服务',overview?.merchants.active,'当前可开展营业'],['已停用',overview?.merchants.suspended,'保留老板只读能力'],['待激活邀请',overview?.invitations.pending,'等待老板完成激活'],['近 30 天新增',overview?.merchants.new_30_days,'按商家开通时间统计']].map(([label,value,note])=><div key={String(label)}><span>{label}</span><strong>{value??'—'}</strong><p>{note}</p></div>)}</div><section className="pc-panel"><div className="pc-section-title"><h2>服务健康</h2><button className="btn-ghost" onClick={()=>setView('operations')}>查看运行详情 →</button></div>{health}</section>{createForm}</>}
 {view==='merchants'&&<>{createForm}<section className="pc-panel"><div className="pc-section-title"><div><h2>商家目录</h2><p>平台超级管理员可直接管理全部商家，无需老板授权。</p></div><Badge>{directory.total} 家</Badge></div><form className="pc-filters" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search)}}><input className="input" aria-label="搜索商家" placeholder="商家名称或编号" value={search} onChange={e=>setSearch(e.target.value)}/><select className="input" aria-label="商家状态筛选" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">全部服务状态</option><option value="active">正常服务</option><option value="suspended">已停用</option></select><select className="input" aria-label="激活状态筛选" value={activated} onChange={e=>{setActivated(e.target.value);setPage(1)}}><option value="all">全部激活状态</option><option value="pending">待激活</option><option value="activated">已激活</option><option value="expired">已过期</option></select><button className="btn-secondary">搜索</button></form><div className="pc-table-wrap"><table><thead><tr><th>商家</th><th>会员模式</th><th>服务状态</th><th>老板邀请</th><th>开通时间</th><th>管理</th></tr></thead><tbody>{directory.items.map((m:any)=><tr key={m.id}><td><strong>{m.name}</strong><small>{m.code}</small></td><td>{m.member_mode==='store'?'单店独立':'商家通用'}</td><td><Badge good={m.status==='active'}>{m.status==='active'?'正常服务':'已停用'}</Badge></td><td>{activation(m.activation)}</td><td>{date(m.created_at)}</td><td><div className="pc-row-actions"><AsyncButton className="btn-primary" onClick={async()=>{const session=await request('/merchants/'+m.id+'/admin-session','POST',{});useAuth.getState().setBootstrap(session);location.assign('/')}}>超级管理</AsyncButton><button className="btn-ghost" onClick={()=>setRecoveryMerchant(m)}>备份恢复</button><button className="btn-ghost" onClick={()=>setStoreMerchant(m)}>门店管理</button><button className="btn-ghost" onClick={()=>{setEditing(m);setName(m.name);setReason('')}}>资料</button><AsyncButton className="btn-ghost" onClick={async()=>{const state=await request('/merchants/'+m.id+'/invite');setInviteState(state);setInviteMerchant(m)}}>老板邀请</AsyncButton><button className="btn-ghost" onClick={()=>{setStatusTarget(m);setReason('')}}>{m.status==='active'?'停用商家':'恢复商家'}</button></div></td></tr>)}</tbody></table></div>{!directory.items.length&&!loading&&<Empty>没有符合条件的商家。可调整筛选，或开通第一家商家。</Empty>}<div className="pc-pagination"><span>共 {directory.total} 家 · 第 {page} 页</span><button className="btn-secondary" disabled={page===1||loading} onClick={()=>setPage(page-1)}>上一页</button><button className="btn-secondary" disabled={page*20>=directory.total||loading} onClick={()=>setPage(page+1)}>下一页</button></div></section></>}
 {['support','merchants'].includes(view)&&recoveryMerchant&&<PlatformRecovery key={recoveryMerchant.id} merchantId={recoveryMerchant.id} merchantName={recoveryMerchant.name} request={request}/>}
 {view==='support'&&<section className="pc-panel"><div className="pc-section-title"><div><h2>历史支持授权</h2><p>旧支持会话保留原授权范围。平台超级管理请到“商家管理”，无需老板授权，不受此处期限限制。</p></div></div>{!grants.length&&<Empty>暂无历史支持授权。可直接在“商家管理”进入超级管理。</Empty>}{grants.map(g=>{const live=!g.revoked_at&&new Date(g.expires_at)>new Date();return <div className="pc-support-row" key={g.id}><div><strong>{g.merchant_name}</strong><p>{g.scope==='maintenance'?'完整维护':g.scope==='configuration'?'配置维护':'只读访问'} · {date(g.expires_at)} 到期</p></div><Badge good={live}>{g.revoked_at?'已撤销':live?'授权有效':'已过期'}</Badge>{live&&<div className="pc-row-actions"><AsyncButton className="btn-secondary" onClick={async()=>{await request('/support-grants/'+g.id+'/revoke','POST',{});await load()}}>结束授权</AsyncButton>{g.scope==='maintenance'&&<button className="btn-secondary" onClick={()=>setRecoveryMerchant({id:g.merchant_id,name:g.merchant_name})}>备份恢复</button>}<AsyncButton className="btn-primary" onClick={async()=>{const session=await request('/support-grants/'+g.id+'/session','POST');useAuth.getState().setBootstrap(session);location.assign('/')}}>进入支持会话</AsyncButton></div>}</div>})}</section>}
 {view==='audit'&&<section className="pc-panel"><div className="pc-section-title"><div><h2>平台操作记录</h2><p>追溯操作者、商家、操作时间与变更内容。</p></div><Badge>{activity.total} 条</Badge></div><form className="pc-filters" onSubmit={e=>{e.preventDefault();setAuditPage(1);setAuditQuery(auditSearch);setAuditFilter({from,to})}}><input className="input" aria-label="搜索审计" placeholder="商家、操作者或操作代码" value={auditSearch} onChange={e=>setAuditSearch(e.target.value)}/><input className="input" aria-label="审计开始日期" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="input" aria-label="审计结束日期" type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="btn-secondary">查询</button></form><div className="pc-table-wrap"><table><thead><tr><th>时间</th><th>操作</th><th>操作者</th><th>关联商家</th><th>详情</th></tr></thead><tbody>{activity.items.map((row:any)=><tr key={row.id}><td>{date(row.created_at)}</td><td><strong>{actionName(row.action)}</strong><small>{row.action}</small></td><td>{row.operator_name??'系统'}</td><td>{row.merchant_name??'平台'}</td><td><button className="btn-ghost" onClick={()=>setDetail(row)}>查看详情</button></td></tr>)}</tbody></table></div>{!activity.items.length&&!loading&&<Empty>当前条件下没有操作记录。</Empty>}<div className="pc-pagination"><span>共 {activity.total} 条 · 第 {auditPage} 页</span><button className="btn-secondary" disabled={auditPage===1||loading} onClick={()=>setAuditPage(auditPage-1)}>上一页</button><button className="btn-secondary" disabled={auditPage*20>=activity.total||loading} onClick={()=>setAuditPage(auditPage+1)}>下一页</button></div></section>}
 {view==='operations'&&<><section className="pc-panel"><div className="pc-section-title"><div><h2>运行与备份</h2><p>来自当前服务和独立备份监测的实时读取结果。</p></div><Badge>读取时间 {date(operations?.checked_at)}</Badge></div>{health}</section><div className="pc-two-columns"><section className="pc-panel"><h2>应用运行</h2><dl><dt>当前版本</dt><dd>{operations?.runtime?.version??'—'}</dd><dt>运行时长</dt><dd>{operations?Math.floor(operations.runtime.uptime_seconds/60)+' 分钟':'—'}</dd><dt>进程内存</dt><dd>{operations?(operations.runtime.rss_bytes/1024**2).toFixed(1)+' MiB':'—'}</dd><dt>最近任务成功</dt><dd>{date(operations?.jobs?.jobs?.last_success_at)}</dd><dt>任务异常</dt><dd>{operations?.jobs?.jobs?.error??(operations?.jobs?.healthy?'无':'尚未确认')}</dd></dl><p className="pc-footnote">显示当前进程状态；发布与回滚通过受控运维流程执行。</p></section><section className="pc-panel"><h2>数据保障</h2><dl><dt>最近备份</dt><dd>{date(operations?.backup?.latest_backup_at)}</dd><dt>监测时间</dt><dd>{date(operations?.backup?.checked_at)}</dd><dt>剩余磁盘</dt><dd>{operations?.backup?.disk_free_bytes!=null?(operations.backup.disk_free_bytes/1024**3).toFixed(1)+' GiB':'未知'}</dd><dt>监测问题</dt><dd>{operations?.backup?.problems?.length?operations.backup.problems.map((p:string)=>({DISK_SPACE_LOW:'磁盘空间不足',BACKUP_STALE:'备份过期',MONITOR_STALE:'监测过期',BACKUP_STATUS_UNAVAILABLE:'监测文件不可用'}[p]??p)).join('、'):'无'}</dd></dl><p className="pc-footnote">每日备份，保留 30 天。恢复先校验临时库，再按授权商家执行。</p></section></div><section className="pc-panel"><h2>渠道与设备接入边界</h2><p className="pc-footnote">支付、团购、小票打印机和读卡器已预留独立接口。服务商授权、设备连接及实际联调尚未完成；各商家在本商家配置中独立管理接入。</p></section></>}
 {view==='security'&&<><section className="pc-panel"><div className="pc-section-title"><div><h2>当前平台账号</h2><p>{user?.name} · {user?.username} · 平台管理员</p></div><Badge>独立平台会话</Badge></div><div className="pc-form-grid">{(['current','next','confirm'] as const).map(key=><label key={key}>{{current:'当前密码',next:'新密码（8–20 位字符）',confirm:'确认新密码'}[key]}<PasswordInput className="input" type="password" autoComplete={key==='current'?'current-password':'new-password'} value={password[key]} onChange={e=>setPassword({...password,[key]:e.target.value})}/></label>)}</div><div className="pc-form-footer"><p>修改后所有平台会话立即失效，需要重新登录。</p><AsyncButton className="btn-primary" onClick={async()=>{if(password.next!==password.confirm)throw Error('两次新密码不一致');await request('/account/password','POST',{current_password:password.current,new_password:password.next});clear()}}>修改密码并重新登录</AsyncButton></div></section><section className="pc-panel"><h2>有效登录会话</h2><p className="pc-footnote">显示当前账号最近 100 条未过期会话，可撤销不再使用的登录。</p>{sessions.map(s=><div className="pc-support-row" key={s.id}><div><strong>{s.current?'当前会话':'其他登录会话'}</strong><p>创建 {date(s.created_at)} · 到期 {date(s.expires_at)}</p><small>{s.id}</small></div><AsyncButton className="btn-secondary" onClick={async()=>{await request('/sessions/'+s.id+'/revoke','POST',{});if(s.current)clear();else await load()}}>{s.current?'退出当前会话':'撤销会话'}</AsyncButton></div>)}</section></>}
 </div><footer className="pc-footer">ZA Thera｜澜序 <span>让门店，自成秩序。</span></footer></main>
 <Modal open={!!editing} title="商家资料" onClose={()=>setEditing(null)}><div className="space-y-4"><p>商家编号：{editing?.code} · 商家身份及会员模式保持不变。</p><label className="block">商家显示名称<input className="input" value={name} onChange={e=>setName(e.target.value)}/></label><label className="block">变更原因<input className="input" value={reason} onChange={e=>setReason(e.target.value)}/></label><AsyncButton className="btn-primary" onClick={async()=>{await request('/merchants/'+editing.id+'/profile','PATCH',{name,previous_name:editing.name,reason});setEditing(null);await load()}}>保存商家资料</AsyncButton></div></Modal>
 <Modal open={!!statusTarget} title={statusTarget?.status==='active'?'停用商家':'恢复商家'} onClose={()=>setStatusTarget(null)}><div className="space-y-4"><p>{statusTarget?.name}（{statusTarget?.code}）</p><p>{statusTarget?.status==='active'?'停用后暂停新营业和营销，老板保留只读及导出能力，在途支付回调继续处理。':'恢复后员工可按原有授权继续营业。'}</p><label className="block">操作原因<input className="input" value={reason} onChange={e=>setReason(e.target.value)}/></label><AsyncButton className="btn-primary" onClick={async()=>{if(!reason.trim())throw Error('请填写操作原因');await request('/merchants/'+statusTarget.id+'/status','PATCH',{status:statusTarget.status==='active'?'suspended':'active',reason});setStatusTarget(null);await load()}}>确认变更</AsyncButton></div></Modal>
 {storeMerchant&&<PlatformStores merchant={storeMerchant} request={request} onClose={()=>setStoreMerchant(null)}/>}<Modal open={!!detail} title="审计详情" onClose={()=>setDetail(null)}><div className="space-y-3"><p>{detail&&actionName(detail.action)} · {date(detail?.created_at)}</p><p>操作者：{detail?.operator_name??'系统'} · 商家：{detail?.merchant_name??'平台'}</p><pre className="pc-json">{JSON.stringify(detail?.detail,null,2)}</pre></div></Modal>
 <Modal open={!!inviteMerchant} title={`老板邀请：${inviteMerchant?.name??''}`} onClose={()=>setInviteMerchant(null)}>{inviteState&&<div className="space-y-4"><p>{activation(inviteState.status)}</p><p>有效期至 {date(inviteState.expires_at)}</p><p className="text-sm text-gray-500">补发后旧链接立即失效。已经激活的老板账号不能重新创建。</p>{inviteState.activation_url&&<input aria-label="补发老板邀请链接" className="input" readOnly value={inviteState.activation_url}/>}<div className="flex gap-3 flex-wrap"><AsyncButton className="btn-primary" disabled={!!inviteState.used_at||inviteMerchant?.status!=='active'} onClick={async()=>{setInviteState(await request('/merchants/'+inviteMerchant.id+'/invite/reissue','POST',{}));setInvite(null);await load()}}>补发老板邀请</AsyncButton><AsyncButton className="btn-secondary" disabled={!!inviteState.used_at||inviteState.status==='expired'} onClick={async()=>{setInviteState(await request('/merchants/'+inviteMerchant.id+'/invite/revoke','POST',{}));setInvite(null);await load()}}>撤销当前邀请</AsyncButton>{inviteState.activation_url&&<AsyncButton className="btn-secondary" onClick={()=>navigator.clipboard.writeText(inviteState.activation_url)}>复制新邀请</AsyncButton>}</div></div>}</Modal></div>
}



