import {useCallback,useEffect,useRef,useState} from 'react'
import BrandMark from '../components/BrandMark'
import {BRAND_NAME} from '../../../shared/brand'
import {getServerUrl} from '../api/transport'
import {fmtDateTime,fmtMoney} from '../utils/format'
const labels:Record<string,string>={pending:'预约已确认',offered:'候补名额待确认',waiting:'候补中',converted:'候补已确认',expired:'候补已过期',cancelled:'已取消',arrived:'已到店',completed:'已完成'}
type Credential={kind:'reservations'|'waitlist';id:number;token:string}
type Pending={path:string;body:unknown;key:string;token?:string;kind?:Credential['kind']}
function stored(key:string){try{return JSON.parse(sessionStorage.getItem(key)??'null')}catch{return null}}
export default function PublicBooking(){
 const parts=location.pathname.split('/'),merchant=decodeURIComponent(parts[2]??''),store=decodeURIComponent(parts[3]??''),base=`${getServerUrl()}/api/public/v1/${encodeURIComponent(merchant)}/${encodeURIComponent(store)}/booking`,storage=`za-spa-saas:booking:v1:${base}`
 const [credential,setCredential]=useState<Credential|null>(()=>stored(storage)),[pending,setPending]=useState<Pending|null>(()=>stored(storage+':pending'))
 const [info,setInfo]=useState<any>(null),[booking,setBooking]=useState<any>(null),[waitlist,setWaitlist]=useState<any>(null),[quote,setQuote]=useState<any>(null),[error,setError]=useState(''),[full,setFull]=useState(false),[busy,setBusy]=useState(false),[newTime,setNewTime]=useState('')
 const [form,setForm]=useState({customer_name:'',customer_phone:'',service_item_id:'',technician_id:'',reserve_time:'',people:1,remark:''}),lock=useRef(false),mounted=useRef(true),generation=useRef(0)
 const request=useCallback(async(path:string,options:RequestInit={})=>{const controller=new AbortController(),abort=()=>controller.abort(),timer=setTimeout(abort,20000);if(options.signal?.aborted)abort();options.signal?.addEventListener('abort',abort,{once:true});try{const response=await fetch(base+path,{...options,signal:controller.signal,credentials:'omit'}),body=await response.json();if(!response.ok||!body.ok)throw Object.assign(Error(body.message??'操作失败'),{status:response.status,code:body.code});return body.data}finally{clearTimeout(timer);options.signal?.removeEventListener('abort',abort)}},[base])
 const load=useCallback(async(signal?:AbortSignal)=>{const id=++generation.current;try{const options=await request('/options',{signal});let row:any=null,reservation:any=null;if(credential){row=await request('/'+credential.kind+'/'+credential.id,{signal,headers:{Authorization:'Bearer '+credential.token}});reservation=credential.kind==='reservations'?row:row.offered_reservation_id?await request('/reservations/'+row.offered_reservation_id,{signal,headers:{Authorization:'Bearer '+credential.token}}):null}if(id!==generation.current||!mounted.current)return;setInfo(options);if(credential){setBooking(reservation);if(credential.kind==='waitlist')setWaitlist(row)}}catch(e){if(!signal?.aborted&&id===generation.current&&mounted.current)setError(e instanceof Error?e.message:'读取失败')}},[request,credential])
 useEffect(()=>{mounted.current=true;const abort=new AbortController();void load(abort.signal);const timer=setInterval(()=>{if(!document.hidden&&!lock.current)void load(abort.signal)},30000);return()=>{mounted.current=false;generation.current++;abort.abort();clearInterval(timer)}},[load])
 function body(){return {...form,service_item_id:Number(form.service_item_id),technician_id:form.technician_id?Number(form.technician_id):null,reserve_time:new Date(form.reserve_time+':00+08:00').toISOString()}}
 function change(next:Partial<typeof form>){setForm(old=>({...old,...next}));setQuote(null);setFull(false)}
 async function estimate(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{setQuote(await request('/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body())}));setFull(false)}catch(e){setFull((e as any)?.code==='BOOKING_FULL');setError(e instanceof RangeError?'请选择预约时间':e instanceof Error?e.message:'报价读取失败')}finally{lock.current=false;setBusy(false)}}
 async function submit(item:Pending){if(lock.current)return;lock.current=true;generation.current++;setBusy(true);setError('');setPending(item);const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),20000);let sent=false
  try{sessionStorage.setItem(storage+':pending',JSON.stringify(item));sent=true;const result=await request(item.path,{method:'POST',signal:abort.signal,headers:{'Content-Type':'application/json','Idempotency-Key':item.key,...(item.token?{Authorization:'Bearer '+item.token}:{})},body:JSON.stringify(item.body)});if(!mounted.current)return
   if(item.kind){const saved={kind:item.kind,id:result.id,token:result.token};sessionStorage.setItem(storage,JSON.stringify(saved));setCredential(saved)}else{generation.current++;setBooking(result);if(credential?.kind==='waitlist')setWaitlist((old:any)=>old?{...old,status:item.path.endsWith('/confirm')?'converted':item.path.endsWith('/cancel')?'cancelled':old.status}:old)}
   sessionStorage.removeItem(storage+':pending');setPending(null)
  }catch(e){if(!mounted.current)return;if(!sent||((e as any)?.status&& (e as any).status<500)){sessionStorage.removeItem(storage+':pending');setPending(null)}setError(!sent?'浏览器无法保存操作凭据，请检查存储权限后重试':e instanceof Error&&e.name!=='AbortError'?e.message:'结果尚未确认，请按原请求重试')}
  finally{clearTimeout(timer);lock.current=false;if(mounted.current)setBusy(false)}
 }
 function create(kind:Credential['kind']){try{void submit({path:'/'+kind,kind,body:body(),key:crypto.randomUUID()})}catch{setError('请选择有效预约时间')}}
 function act(action:string,data:unknown){if(booking&&credential)void submit({path:'/reservations/'+booking.id+'/'+action,body:data,key:crypto.randomUUID(),token:credential.token})}
 const blocked=busy||!!pending
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-8"><section className="max-w-xl mx-auto space-y-5"><header className="flex gap-3 items-center"><BrandMark/><div><p className="text-xs tracking-widest text-brand-700">{BRAND_NAME} · 顾客预约</p><h1 className="text-2xl font-semibold mt-1">{info?.store.name??'正在读取门店…'}</h1></div></header>{error&&<p role="alert" className="card p-4 text-red-600">{error}</p>}{pending&&<div className="card p-4"><p>上次操作结果尚未确认。已保留原请求，可安全核对。</p><button className="btn-primary mt-3" disabled={busy} onClick={()=>void submit(pending)}>核对原操作结果</button></div>}
 {!credential&&<form className="card p-5 space-y-4" onSubmit={e=>{e.preventDefault();void estimate()}}><fieldset className="space-y-4" disabled={blocked||!info?.store.available}><label className="block">您的称呼<input className="input w-full" required maxLength={64} value={form.customer_name} onChange={e=>change({customer_name:e.target.value})}/></label><label className="block">手机号码<input className="input w-full" type="tel" required pattern="1[0-9]{10}" value={form.customer_phone} onChange={e=>change({customer_phone:e.target.value})}/></label><label className="block">预约项目<select className="input w-full" required value={form.service_item_id} onChange={e=>change({service_item_id:e.target.value})}><option value="">请选择项目</option>{info?.services.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {fmtMoney(s.price)}</option>)}</select></label><label className="block">指定技师<select className="input w-full" value={form.technician_id} onChange={e=>change({technician_id:e.target.value})}><option value="">不指定</option>{info?.technicians.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label>预约时间（北京时间）<input className="input w-full" type="datetime-local" required value={form.reserve_time} onChange={e=>change({reserve_time:e.target.value})}/></label><label>到店人数<input className="input w-full" type="number" min={1} max={20} required value={form.people} onChange={e=>change({people:Number(e.target.value)})}/></label></div><label className="block">备注<textarea className="input w-full" maxLength={500} value={form.remark} onChange={e=>change({remark:e.target.value})}/></label><button className="btn-secondary w-full" type="submit">查看时段与价格</button></fieldset>{quote&&<div className="rounded-lg bg-brand-50 p-4"><p>参考总价 {fmtMoney(quote.total_price)} · {quote.duration} 分钟</p>{quote.deposit_required>0?<p className="text-sm mt-2">需订金 {fmtMoney(quote.deposit_required)}。线上支付尚未接入，请联系门店预约。</p>:<button type="button" className="btn-primary w-full mt-3" disabled={blocked} onClick={()=>create('reservations')}>确认预约</button>}</div>}{full&&<button type="button" className="btn-primary w-full" disabled={blocked} onClick={()=>create('waitlist')}>加入此时段候补</button>}{info&&!info.store.available&&<p>门店暂未接受新预约。</p>}</form>}
 {credential&&<div className="card p-5 space-y-4"><p role="status" className="text-xl font-semibold">{labels[booking?.status??waitlist?.status]??'正在读取预约…'}</p>{waitlist?.expires_at&&waitlist.status==='offered'&&<p>请在 {fmtDateTime(waitlist.expires_at)} 前确认名额。</p>}{booking&&<><p>{booking.customer_name} · {booking.people} 位</p><p>{fmtDateTime(booking.reserve_time)} · {booking.duration} 分钟</p>{booking.status==='offered'&&<button className="btn-primary" disabled={blocked} onClick={()=>act('confirm',{version:booking.version})}>确认候补名额</button>}{booking.status==='pending'&&<label className="block">改期时间（北京时间）<input className="input w-full" type="datetime-local" disabled={blocked} value={newTime} onChange={e=>setNewTime(e.target.value)}/><button className="btn-secondary mt-2" disabled={blocked||!newTime} onClick={()=>act('reschedule',{version:booking.version,reserve_time:new Date(newTime+':00+08:00').toISOString()})}>确认改期</button></label>}{['pending','offered'].includes(booking.status)&&<button className="btn-secondary" disabled={blocked} onClick={()=>act('cancel',{version:booking.version})}>取消预约</button>}</>}{['cancelled','expired','completed'].includes(booking?.status??waitlist?.status)&&<button className="btn-primary" disabled={blocked} onClick={()=>{sessionStorage.removeItem(storage);setCredential(null);setBooking(null);setWaitlist(null);setQuote(null)}}>重新预约</button>}<button className="btn-secondary" disabled={blocked} onClick={()=>void load()}>刷新状态</button></div>}
 <p className="text-xs text-gray-500 text-center">请保留此页面查看预约；候补名额在页面更新，不会自动发送短信。</p></section></main>
}
