import {recoveryRouter} from './routes/recovery.js';
import express from 'express';
import cors from 'cors';
import {randomUUID} from 'node:crypto';
import {platformPool} from './db/pools.js';
import {errorHandler} from './errors.js';
import {platformRouter,merchantRouter} from './routes/auth.js';
import {platformConsoleRouter} from './routes/platform-console.js';
import {organizationRouter} from './routes/organization.js';
import {catalogRouter} from './routes/catalog.js';
import {membersRouter} from './routes/members.js';
import {cashierRouter} from './routes/cashier.js';
import {orderActionsRouter} from './routes/order-actions.js';
import {clocksRouter} from './routes/clocks.js';
import {inventoryRouter} from './routes/inventory.js';
import {permissionsRouter} from './routes/permissions.js';
import {settingsRouter} from './routes/settings.js';
import {shiftsRouter} from './routes/shifts.js';
import {memberInsightsRouter} from './routes/member-insights.js';
import {couponsRouter} from './routes/coupons.js';
import {reservationsRouter} from './routes/reservations.js';
import {queueRouter} from './routes/queue.js';
import {publicRouter} from './routes/public.js';
import {approvalsRouter} from './routes/approvals.js';
import {storeOperationsRouter} from './routes/store-operations.js';
import {rulesRouter} from './routes/rules.js';
import {reportsRouter} from './routes/reports.js';
import {templatesRouter} from './routes/templates.js';
import {roomWarningsRouter} from './routes/room-warnings.js';
import {technicianOperationsRouter} from './routes/technician-operations.js';
import {exportsRouter} from './routes/exports.js';
import {marketingRouter} from './routes/marketing.js';
import {integrationsRouter} from './routes/integrations.js';
import {devicesRouter} from './routes/devices.js';
import {gatewayManagementRouter,hardwareGatewayRouter} from './routes/hardware-gateway.js';
import {paymentProvidersRouter} from './routes/payment-providers.js';
import {platformRoute} from './access.js';
import {backupHealth} from './services/operations-health.js';
import {publicBookingRouter} from './routes/public-booking.js';
import {bookingWaitlistRouter} from './routes/booking-waitlist.js';
import {couponClaimsRouter,publicCouponClaimsRouter} from './routes/coupon-claims.js';
import {patrolRouter} from './routes/patrol.js';
import {maintenanceRouter} from './routes/maintenance.js';
import {wristbandsRouter} from './routes/wristbands.js';
import {captureRequest} from './services/maintenance.js';
export function createApp(health?:()=>{healthy:boolean;jobs?:unknown}){
 const app=express();app.disable('x-powered-by');app.set('trust proxy','loopback');
 const origins=new Set([process.env.PUBLIC_ORIGIN,'zaspa-saas://app',...(process.env.NODE_ENV!=='production'?['http://127.0.0.1:5175','http://localhost:5175','http://127.0.0.1:5176']:[])].filter(Boolean));
 app.use(cors({origin:(origin,callback)=>callback(null,!origin||origins.has(origin)),credentials:false}));
 app.use((req,res,next)=>{res.locals.requestId=randomUUID();res.setHeader('X-Request-ID',res.locals.requestId);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');next()});
 app.use(express.json({limit:'256kb'}));
 app.use((req,res,next)=>{const start=performance.now();res.once('finish',()=>{const scope=res.locals.diagnosticScope;if(scope&&!req.path.includes('/maintenance/')&&!req.path.endsWith('/session')&&!req.path.includes('/realtime/'))captureRequest({...scope,requestId:res.locals.requestId,method:req.method,route:'/api/merchant/v1'+String(req.route?.path??''),status:res.statusCode,duration:performance.now()-start})});next()});
 app.get('/ready',async(_req,res,next)=>{try{await platformPool.query('SELECT 1');const state=health?.();res.status(state?.healthy===false?503:200).json({ok:state?.healthy!==false,service:'za-spa-saas',version:'1.0.22',...(state?.jobs?{jobs:state.jobs}:{})})}catch(e){next(e)}});
 app.use('/api/platform/v1',platformRouter);
 app.use('/api/platform/v1',platformConsoleRouter);
 app.use('/api/platform/v1',recoveryRouter);
 app.get('/api/platform/v1/operations',platformRoute(async()=>{await platformPool.query('SELECT 1');return {checked_at:new Date().toISOString(),database:'healthy',jobs:health?.()??{healthy:false,status:'unavailable'},backup:await backupHealth(),runtime:{version:'1.0.22',uptime_seconds:Math.floor(process.uptime()),rss_bytes:process.memoryUsage().rss}}}));
 app.use('/api/merchant/v1',exportsRouter);
 app.use('/api/merchant/v1',marketingRouter);
 app.use('/api/merchant/v1',integrationsRouter);
 app.use('/api/merchant/v1',devicesRouter);
 app.use('/api/merchant/v1',gatewayManagementRouter);
 app.use('/api/hardware/v1',hardwareGatewayRouter);
 app.use('/api/merchant/v1',paymentProvidersRouter);
 app.use('/api/public/v1',publicRouter);
 app.use('/api/public/v1',publicBookingRouter);
 app.use('/api/merchant/v1',bookingWaitlistRouter);
 app.use('/api/merchant/v1',couponClaimsRouter);
 app.use('/api/merchant/v1',patrolRouter);
 app.use('/api/merchant/v1',maintenanceRouter);
 app.use('/api/merchant/v1',wristbandsRouter);
 app.use('/api/public/v1',publicCouponClaimsRouter);
 app.use('/api/merchant/v1',merchantRouter,organizationRouter,permissionsRouter,settingsRouter,shiftsRouter,catalogRouter,memberInsightsRouter,membersRouter,couponsRouter,reservationsRouter,queueRouter,approvalsRouter,storeOperationsRouter,rulesRouter,reportsRouter,templatesRouter,cashierRouter,orderActionsRouter,roomWarningsRouter,technicianOperationsRouter,clocksRouter,inventoryRouter);
 app.use((_req,res)=>res.status(404).json({ok:false,code:'NOT_FOUND',message:'接口不存在'}));
 app.use(errorHandler);return app;
}


