ALTER TABLE items ALTER COLUMN stock TYPE numeric(18,3);
ALTER TABLE items ADD CHECK(stock=-1 OR stock>=0);
ALTER TABLE items ADD CHECK(price>=0 AND cost>=0 AND duration>=0);
ALTER TABLE inventory_movements ALTER COLUMN qty TYPE numeric(18,3);
ALTER TABLE inventory_movements ADD COLUMN delta numeric(18,3) NOT NULL DEFAULT 0;
ALTER TABLE inventory_movements ADD COLUMN balance_after numeric(18,3);
ALTER TABLE inventory_movements ADD COLUMN source_type text;
ALTER TABLE inventory_movements ADD COLUMN source_id text;
ALTER TABLE inventory_movements ADD COLUMN reversal_of bigint;
ALTER TABLE inventory_movements ADD UNIQUE(merchant_id,reversal_of);
ALTER TABLE inventory_movements ADD FOREIGN KEY(merchant_id,store_id,reversal_of) REFERENCES inventory_movements(merchant_id,store_id,id);
ALTER TABLE order_items ADD COLUMN inventory_movement_id bigint;
ALTER TABLE order_items ADD FOREIGN KEY(merchant_id,store_id,inventory_movement_id) REFERENCES inventory_movements(merchant_id,store_id,id);
ALTER TABLE order_items ADD CHECK(quantity>0 AND price>=0 AND amount>=0 AND duration>=0);
ALTER TABLE orders ADD CHECK(subtotal>=0 AND discount>=0 AND payable>=0 AND paid>=0 AND deposit>=0);
ALTER TABLE payments ADD COLUMN asset_operation_id bigint;
ALTER TABLE payments ADD COLUMN shift_id bigint;
ALTER TABLE payments ADD FOREIGN KEY(merchant_id,store_id,shift_id) REFERENCES shifts(merchant_id,store_id,id);
ALTER TABLE payments ADD FOREIGN KEY(merchant_id,asset_operation_id) REFERENCES asset_operations(merchant_id,id);
ALTER TABLE payments ADD CHECK(amount>0);
CREATE UNIQUE INDEX payment_voucher_once ON payments(merchant_id,store_id,upper(trim(voucher_code))) WHERE voucher_code IS NOT NULL AND reversed_at IS NULL;
GRANT DELETE ON categories,member_levels TO saas_runtime;
CREATE UNIQUE INDEX wristband_one_live_order ON orders(merchant_id,store_id,wristband_no) WHERE wristband_no IS NOT NULL AND status IN('open','suspended');
