import {useCallback,useRef,useState} from 'react'
import {remote,isRemoteFailure} from '../api/transport'
import {useAuth,canWriteBusiness} from '../store/auth'
import {useAutoRefresh} from '../hooks/useAutoRefresh'
import {AsyncButton,Modal,EmptyState} from './ui'
import {fmtMoney} from '../utils/format'
const empty={version:0,name:'',type:'cash',value:0,min_amount:0,expire_days:30,active:false,max_claims:100}
type Pending={path:string;body:unknown;key:string;kind:'save'|'invite'}
export default function CouponCampaigns({manage=true}:{manage?:boolean}){
 const [rows,setRows]=useState<any[]>([]),[form,setForm]=useState<any>(null),[selected,setSelected]=useState<any>(null),[members,setMembers]=useState<any[]>([]),[query,setQuery]=useState(''),[member,setMember]=useState(''),[reason,setReason]=useState(''),[verified,setVerified]=useState(false),[link,setLink]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false)
 const running=useRef(false),pending=useRef<Pending|null>(null),realm=useAuth(s=>s.realm),merchant=useAuth(s=>s.merchant),writable=canWriteBusiness()
 const load=useCallback(async()=>{try{setRows(await remote<any[]>('/api/merchant/v1/coupon-campaigns'))}catch(e){setError(e instanceof Error?e.message:'活动加载失败')}},[]);useAutoRefresh(load)
 async function submit(item:Pending){if(running.current)return;running.current=true;setBusy(true);setError('');pending.current=item
  try{const result=await remote<any>('/api/merchant/v1/coupon-campaigns'+item.path,{method:'POST',headers:{'Idempotency-Key':item.key},body:JSON.stringify(item.body)});if(isRemoteFailure(result)){setUnknown(result.code==='RESULT_UNKNOWN');setError(result.msg);return}setUnknown(false);pending.current=null;if(item.kind==='save'){setRows(old=>[result,...old.filter(r=>r.id!==result.id)]);setForm(null)}else setLink(result.claim_url)}catch(e){setUnknown(true);setError(e instanceof Error?e.message:'结果尚未确认')}finally{running.current=false;setBusy(false)}
 }
 const retry=<button className="btn-primary" disabled={busy} onClick={()=>pending.current&&void submit(pending.current)}>原请求重试</button>,blocked=busy||unknown
 function save(){if(!form.name.trim()||form.value<=0||form.type==='discount'&&form.value>1||form.min_amount<0||!Number.isInteger(form.expire_days)||form.expire_days<1||form.expire_days>365||!Number.isInteger(form.max_claims)||form.max_claims<1){setError('请检查券名、面值、门槛、有效天数与总量');return}const keys=['id','version','name','type','value','min_amount','expire_days','active','max_claims'];void submit({path:'',body:Object.fromEntries(keys.filter(k=>form[k]!==undefined).map(k=>[k,form[k]])),key:crypto.randomUUID(),kind:'save'})}
 return <div className="space-y-4 max-w-5xl"><div className="card p-5 flex justify-between gap-3"><div><h3 className="font-semibold">领券活动</h3><p className="text-sm text-gray-500 mt-1">每位会员每个活动限领一次。先由门店核验身份，再生成 30 分钟有效的专属领券链接；手机号验证接口尚未接入。</p></div>{manage&&<button className="btn-primary" disabled={!writable||blocked} onClick={()=>{setForm({...empty});setError('')}}>新增领券活动</button>}</div>{error&&!form&&!selected&&<p role="alert" className="text-red-600">{error}</p>}<div className="card overflow-auto"><table className="table w-full"><thead><tr><th>活动</th><th>权益</th><th>领取数量</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.type==='cash'?fmtMoney(row.value):`${Number(row.value)*10} 折`} · 满 {fmtMoney(row.min_amount)}<div className="text-xs">领取后 {row.expire_days} 天有效</div></td><td>{row.issued_count} / {row.max_claims}</td><td>{row.active?'启用中':'已停用'}</td><td>{manage&&<button className="btn-secondary mr-2" disabled={!writable||blocked} onClick={()=>{setForm({...row});setError('')}}>编辑活动</button>}<button className="btn-secondary" disabled={!writable||blocked||!row.active||row.issued_count>=row.max_claims} onClick={()=>{setSelected(row);setMembers([]);setQuery('');setMember('');setReason('');setVerified(false);setLink('');setError('')}}>核验并生成领券链接</button></td></tr>)}</tbody></table>{!rows.length&&<EmptyState text="暂无领券活动" />}</div>
 <Modal open={!!form} title="领券活动配置" onClose={()=>{if(!blocked)setForm(null)}} footer={unknown?retry:<button className="btn-primary" disabled={busy} onClick={save}>保存活动</button>}>{form&&<fieldset disabled={blocked} className="space-y-3"><label className="block">活动名称<input className="input w-full" maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="block">优惠类型<select aria-label="优惠类型" className="input w-full" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="cash">代金券</option><option value="discount">折扣券</option></select></label><div className="grid grid-cols-2 gap-3">{[['value',form.type==='cash'?'券面值':'折扣比例（如 0.88）'],['min_amount','消费门槛'],['expire_days','有效天数'],['max_claims','活动总量']].map(([key,label])=><label key={key}>{label}<input className="input w-full" type="number" step={['value','min_amount'].includes(key)?'.01':'1'} value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})}/></label>)}</div><label className="flex gap-2"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>启用领券活动</label>{error&&<p role="alert" className="text-red-600">{error}</p>}</fieldset>}</Modal>
 <Modal open={!!selected} title="核验会员并生成领券链接" onClose={()=>{if(!blocked)setSelected(null)}} footer={unknown?retry:!link?<button className="btn-primary" disabled={busy||!member||!verified||!reason.trim()} onClick={()=>void submit({path:'/'+selected.id+'/invite',body:{member_id:Number(member),verification:'in_person',reason:reason.trim()},key:crypto.randomUUID(),kind:'invite'})}>生成专属领券链接</button>:<AsyncButton className="btn-primary" onClick={()=>navigator.clipboard.writeText(link)}>复制领券链接</AsyncButton>}>
 {link?<div><p>链接有效期 30 分钟，仅可领取该会员的本次活动权益。</p><input aria-label="专属领券链接" className="input w-full mt-3" readOnly value={link}/></div>:<fieldset disabled={blocked} className="space-y-3"><label className="block">查找会员<input className="input w-full" value={query} onChange={e=>setQuery(e.target.value)} placeholder="姓名、手机号或卡号"/></label><AsyncButton className="btn-secondary" disabled={!query.trim()} onClick={async()=>{try{setMembers(await remote<any[]>('/api/merchant/v1/members?limit=20&keyword='+encodeURIComponent(query.trim())));setMember('')}catch(e){setError(e instanceof Error?e.message:'查询失败')}}}>查询会员</AsyncButton><label className="block">待核验会员<select aria-label="待核验会员" className="input w-full" value={member} onChange={e=>setMember(e.target.value)}><option value="">请选择会员</option>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.card_no}</option>)}</select></label><label className="flex gap-2"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>已在门店核对会员身份与卡号</label><label className="block">核验记录<textarea className="input w-full" maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset>}{error&&<p role="alert" className="text-red-600 mt-3">{error}</p>}</Modal></div>
}
