import DeviceQuickSetup from './DeviceQuickSetup'
import {buildGatewaySuggestion,compareDevices,sameSubnet,selectGatewayHost} from '../../../shared/hardware'
import {useRef,useState} from 'react'
import type {HardwareInventory,GatewaySuggestion} from '../../../shared/hardware'
export default function DeviceDiscovery({onGateway,onReader,onAnnouncer,onInvalidate,disabled}:{onGateway:(p:GatewaySuggestion)=>void;onReader:(p:{name:string;transport:string})=>void;onAnnouncer:(p:{name:string;transport:string;port?:string})=>void;onInvalidate:()=>void;disabled:boolean}){
 const [result,setResult]=useState<HardwareInventory|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[host,setHost]=useState(''),[notice,setNotice]=useState('')
 const [changes,setChanges]=useState<ReturnType<typeof compareDevices>|null>(null),[valid,setValid]=useState(false),[onlyChanges,setOnlyChanges]=useState(false)
 const [configPending,setConfigPending]=useState(false)
 const lock=useRef(false)
 return <section className="card p-5 space-y-3" aria-label="一键检测设备"><h3 className="font-semibold">一键检测与配置</h3>
 <p className="text-sm text-gray-500">检测当前电脑的网卡、USB、串口、网关端口及已知局域网邻居。不会修改设备地址、关闭原厂服务或读取原厂账号。设备清单仅在本页显示，不自动上传。</p>
 {!window.saasDesktop?.detectHardware?<p>请使用支持设备检测的 Windows 客户端。网页端无法直接读取本机硬件。</p>:<button className="btn-primary" disabled={busy||disabled||configPending} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setValid(false);onInvalidate();setNotice('');try{const r=await window.saasDesktop!.detectHardware();setChanges(result&&!result.warnings.length&&!r.warnings.length?compareDevices(result.devices,r.devices):null);setResult(r);setValid(true);setHost(selectGatewayHost(r,host))}catch{setError('检测失败，请重试；本次没有更改任何配置。')}finally{lock.current=false;setBusy(false)}}}>{busy?'正在检测（最长约20秒）…':result?'重新检测设备变化':'一键检测本机设备'}</button>}
 {error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {result&&<>{!valid&&<p className="text-amber-700">以下为上次结果；检测成功前不可用于配置。</p>}{changes&&<div role="status" className="border rounded p-3"><p>与上次检测比较：新增 {changes.added.length} 项，移除 {changes.removed.length} 项，状态变化 {changes.changed.length} 项。</p>{changes.removed.map((d,i)=><p key={i}>已移除：{d.name} {d.port}</p>)}<p className="text-xs">可先拔下待识别设备检测，再插回重新检测，通过新增项定位；不会自动认定设备用途。</p></div>}<p className="text-xs text-gray-500">检测时间：{new Date(result.scannedAt).toLocaleString()}，设备插拔或网络变化后请重新检测。</p>{result.warnings.map((w,i)=><p key={i} className="text-amber-700">{w}</p>)}
 <div className="border rounded p-3 space-y-1"><h4 className="font-medium">原厂点钟王本机资料</h4><p>{result.vendor.cacheFound?'已检测到思软硬件缓存':'未检测到思软硬件缓存'} · {result.vendor.menuFound?`菜单资源 ${result.vendor.menuResourceCount} 项`:'未取得菜单资源'} · 已授权设备记录 {result.vendor.authorizedDeviceCount} 项 · 可确认完整绑定 {result.vendor.bindings.length} 项 · 8032在线面板候选 {result.panelCandidates.length} 台</p>{result.vendor.authorizedDevices.map(id=>{const binding=result.vendor.bindings.find(b=>b.deviceId===id),online=binding&&result.panelCandidates.some(c=>c.address===binding.panelIp);return <p className="text-sm" key={id}>设备编号：<code>{id}</code>{binding?` · 房间 ${binding.roomNo} · 面板IP ${binding.panelIp} · ${online?'当前8032在线':'当前未见8032连接'}`:' · 未取得唯一房间/IP关系'}</p>})}{result.panelCandidates.filter(c=>!result.vendor.bindings.some(b=>b.panelIp===c.address)).map(c=><p className="text-sm" key={c.address}>未匹配在线面板：{c.address} → 门店电脑 {c.localAddress}:8032</p>)}<p className="text-xs text-gray-500">原厂缓存可同时确认设备编号、房间和面板IP；在线连接用于交叉核对。同一房间或IP出现多个设备时拒绝自动绑定。注册码、菜单正文及原厂账号不会显示或上传。</p></div>
 <DeviceQuickSetup key={result.scannedAt} inventory={result} onPending={setConfigPending} disabled={disabled||busy||!valid}/><div className="border rounded p-3 space-y-2"><h4 className="font-medium">点钟王网关参数</h4><label>用于门店设备的网卡<select className="input w-full" aria-label="用于门店设备的网卡" disabled={configPending} value={host} onChange={e=>{setHost(e.target.value);onInvalidate();setNotice('网卡已切换，请重新生成推荐参数。')}}><option value="">请选择与面板相连的门店网卡</option>{result.interfaces.map(i=><option key={i.name+i.address} value={i.address}>{i.name} · {i.address} · 掩码 {i.netmask}</option>)}</select></label>{!result.interfaces.length&&<p>未找到局域网IPv4地址，请连接门店网络后重试。</p>}<p>监听端口：{result.ports.map(p=>`${p.port} ${p.available?'检测时可用':'不可用'}`).join('；')}</p><button className="btn-secondary" disabled={disabled||busy||!valid||configPending||!host||!result.ports.some(p=>p.available)} onClick={()=>{const suggestion=buildGatewaySuggestion(result,host,result.ports.find(p=>p.available)!.port);onGateway(suggestion);setNotice(suggestion.bindings.length?'已自动填入网关、设备编号、房间和面板IP，请核对后保存。':result.vendor.authorizedDevices.length?'已填入设备编号；未取得完整房间与面板IP绑定，可从在线候选中选择。':'已生成网关参数建议；未发现原厂授权设备编号，请在下方手动填写。')}}>生成推荐网关配置</button><p className="text-xs text-gray-500">多网卡时必须选择门店网卡。端口可用性和在线连接均为检测时快照，网关启动时仍需检查。</p></div>
 <div className="border rounded p-3 space-y-2"><h4 className="font-medium">USB / 串口候选设备（{result.devices.length}）</h4><p className="text-sm">这些是电脑枚举到的设备，不代表均为刷牌器或报钟器。通过插拔前后对照名称，并刷卡测试确认。</p>{!result.devices.length&&<p>未枚举到候选设备；请检查连接和驱动，不能据此判定门店没有设备。</p>}{changes&&<label className="flex items-center gap-2"><input type="checkbox" checked={onlyChanges} onChange={e=>setOnlyChanges(e.target.checked)}/>仅看新增或状态变化</label>}<div className="max-h-72 overflow-auto">{(changes&&onlyChanges?[...changes.added,...changes.changed]:result.devices).map((d,i)=><div key={i} className="border-b py-2"><p>{changes?.added.includes(d)&&<strong className="text-green-700">新增 · </strong>}{changes?.changed.includes(d)&&<strong className="text-amber-700">状态变化 · </strong>}{d.name||'未命名设备'} · {d.status} · {d.port||d.vidPid||d.kind}</p>{d.kind==='keyboard'?<p className="text-xs">键盘输入候选：需要刷卡确认，普通键盘也会列在这里。</p>:<p className="text-xs">需要匹配厂商驱动/协议，不能仅凭 USB 插口自动启用。</p>}<button className="btn-secondary" disabled={disabled||busy||!valid||configPending||d.status!=='OK'} onClick={()=>{onReader({name:d.name.slice(0,100)||'刷牌器',transport:d.kind==='keyboard'?'keyboard':d.kind==='serial'?'serial':'usb'});setNotice('已填入刷牌器资料草稿，请确认设备身份后保存；这不会安装驱动或完成硬件接通。')}}>选为刷牌器，填写资料</button>{d.kind!=='keyboard'&&<button className="btn-secondary ml-2" disabled={disabled||busy||!valid||configPending||d.status!=='OK'} onClick={()=>{onAnnouncer({name:d.name.slice(0,100)||'播报器',transport:d.kind==='serial'?'serial':'usb',port:d.port});setNotice('已生成播报器资料建议，请在下方确认应用；协议仍需厂商确认。')}}>选为报钟器，填写资料</button>}</div>)}</div></div>
 <details className="border rounded p-3"><summary>已知局域网设备（{result.neighbors.filter(n=>result.interfaces.some(i=>i.address===host&&sameSubnet(n.address,i.address,i.netmask))).length}，当前网卡同网段，身份未识别）</summary><p className="text-sm">请先选择门店网卡；仅显示该网卡同网段的邻居缓存，排除电脑自身及广播地址，可能不完整或过期。IP不能证明设备型号，不会自动绑定房间。</p><div className="max-h-52 overflow-auto">{result.neighbors.filter(n=>result.interfaces.some(i=>i.address===host&&sameSubnet(n.address,i.address,i.netmask))).map((n,i)=><p key={i}>{n.address} · 网卡索引 {n.interfaceIndex} · {n.state}</p>)}</div></details>
 <p className="text-sm text-amber-700">报钟器和点钟王的厂商业务适配尚未完成。检测结果不能代替实机报钟、刷卡和试播验收。</p></>}
 </section>
}
