import type {GatewaySuggestion,GatewayLocalState} from '../../../shared/hardware'
import {gatewayReadiness} from '@za-spa/contracts'
import {useCallback,useEffect,useRef,useState} from 'react'
import {remote,isRemoteFailure,getServerUrl} from '../api/transport'
import {api} from '../api'
import {useAuth,canWriteBusiness} from '../store/auth'
import {useAutoRefresh} from '../hooks/useAutoRefresh'
import {AsyncButton} from './ui'
const ipv4=(s:string)=>/^(?:0|[1-9]\d{0,2})(?:\.(?:0|[1-9]\d{0,2})){3}$/.test(s)&&s.split('.').every(n=>Number(n)<=255)
const emptyPanel=()=>({key:crypto.randomUUID(),room:'',ip:'',device:''})
const path='/api/merchant/v1/devices/gateways'
export default function HardwareGateways({suggestion}:{suggestion?:GatewaySuggestion|null}){
 const user=useAuth(s=>s.user),realm=useAuth(s=>s.realm),merchant=useAuth(s=>s.merchant),stores=useAuth(s=>s.stores),currentStoreId=useAuth(s=>s.currentStoreId)
 const owner=canWriteBusiness()&&user?.role==='owner'
 const currentStore=stores.find(s=>s.id===currentStoreId)
 const [rows,setRows]=useState<any[]>([]),[rooms,setRooms]=useState<any[]>([]),[error,setError]=useState(''),[issued,setIssued]=useState<any>(null),[name,setName]=useState('房间面板联调'),[panels,setPanels]=useState([emptyPanel()]),[host,setHost]=useState('127.0.0.1'),[port,setPort]=useState('18032'),[busy,setBusy]=useState(false),[downloaded,setDownloaded]=useState(false),[requestId,setRequestId]=useState(()=>crypto.randomUUID())
 const localLock=useRef(false),businessLock=useRef(false)
 const [local,setLocal]=useState<GatewayLocalState|null>(null),[localBusy,setLocalBusy]=useState(false)
 useEffect(()=>{if(!window.saasDesktop?.gateway)return;let live=true;const read=()=>window.saasDesktop!.gateway('state').then(s=>{if(live)setLocal(s)}).catch(()=>{if(live)setError('无法读取本机网关状态')});void read();const timer=setInterval(()=>void read(),3000);return()=>{live=false;clearInterval(timer)}},[])
 async function control(action:'start'|'stop'|'check'){
  if(localLock.current||!window.saasDesktop?.gateway)return;localLock.current=true;setLocalBusy(true);setError('');try{setLocal(await window.saasDesktop.gateway(action,action==='start'?{apiOrigin:getServerUrl(),listenHost:issued.listenHost,port:issued.port,storeId:issued.store_id,token:issued.token,devices:issued.devices}:undefined))}catch(e){setError(e instanceof Error?e.message:'本机网关操作失败')}finally{localLock.current=false;setLocalBusy(false)}
 }
 const load=useCallback(async()=>{const [g,r]=await Promise.all([remote<any[]>(path),remote<any[]>('/api/merchant/v1/rooms')]);setRows(g);setRooms(r)},[]);useAutoRefresh(load,30000,{pollWhenConnected:true})
 return <section className="card p-5 space-y-3" aria-label="门店硬件网关"><h3 className="font-semibold">门店硬件网关</h3>
  <p className="text-sm text-gray-500">网关与实体设备的状态分开显示。当前为只读联调，仅可读取已绑定房间的房态和服务信息；不能结账、报钟或下钟。授权7天有效，由老板签发或撤销。</p>
  <div className="border rounded p-3 space-y-2"><h4 className="font-medium">点钟王门店业态</h4><p className="text-sm text-gray-500">厂商菜单按洗浴或足浴业态生成。签发网关授权前必须设置；有效授权期间不能切换。</p><select aria-label="点钟王门店业态" className="input max-w-48" disabled={!owner||busy||!currentStore} value={currentStore?.point_clock_business_type??''} onChange={async e=>{if(!currentStore||businessLock.current)return;businessLock.current=true;setBusy(true);setError('');try{const result=await remote<any>('/api/merchant/v1/stores/'+currentStore.id,{method:'PUT',body:JSON.stringify({name:currentStore.name,short_name:currentStore.short_name??undefined,point_clock_business_type:e.target.value})});if(isRemoteFailure(result)){setError(result.msg);return}await api.refreshSession()}catch(e){setError(e instanceof Error?e.message:'门店业态保存失败，请重新读取后核对')}finally{businessLock.current=false;setBusy(false)}}}><option value="" disabled>请选择门店业态</option><option value="BATH">洗浴</option><option value="FOOT">足浴</option></select>{!currentStore?.point_clock_business_type&&<p role="status" className="text-sm text-amber-700">尚未配置，无法启用原厂点钟王登录菜单。</p>}</div>
  {window.saasDesktop?.gateway&&<div className="border rounded p-3 space-y-2" aria-label="本机网关运行状态"><h4 className="font-medium">本机网关</h4><p role="status">{local?.message??'正在读取本机状态…'}</p>{local?.host&&<p>监听 {local.host}:{local.port}</p>}{local?.devices?.map(d=><p key={d.device_id}>{d.device_id}：{d.state==='connected'?'TCP已连接，业务未验收':d.state==='protocol_error'?'协议不匹配':'未连接'}</p>)}<button className="btn-secondary" disabled={localBusy||!local||local.status==='stopped'} onClick={()=>void control('stop')}>停止本机网关</button><button className="btn-secondary ml-2" disabled={localBusy||!local||!['running','degraded'].includes(local.status)} onClick={()=>void control('check')}>检查网关授权与连接</button><p className="text-xs text-gray-500">当前仅支持只读联调。关闭或刷新客户端、退出账号、切换门店会停止网关；授权撤销后查询立即失败，心跳检测到失效后停止监听。不能替换营业中的厂商服务。</p></div>}
  {rows.map(g=>{const health=gatewayReadiness(g);return <div key={g.id} className="border rounded p-3 space-y-2"><p>{g.name} · {health.label}</p><p className="text-xs text-gray-500">最近心跳：{g.last_seen_at?new Date(g.last_seen_at).toLocaleString():'尚无'} · 到期：{new Date(g.expires_at).toLocaleString()}</p>{!health.fresh&&<p role="status" className="text-sm text-amber-700">下列设备状态仅为历史上报，不能代表当前连接。{health.state==='revoked'||health.state==='expired'?'请由老板重新签发授权。':'请检查门店网关进程、网络和电脑时钟。'}</p>}{g.devices?.map((d:any)=><p key={d.device_id} className="text-sm">房间 {d.room_no} · 面板 {d.device_id} · IP {d.device_ip}{d.active!==1?'（房间已停用）':''}</p>)}{g.device_status.length===0&&<p className="text-sm">尚无设备连接报告，请先在门店电脑运行已配对的网关。</p>}{g.device_status.map((d:any)=><p key={d.device_id} className="text-sm">设备 {d.device_id}：{!health.fresh?'当前状态未知；上次：':''}{({connected:'TCP已连接，业务未验收',disconnected:'未连接',protocol_error:'协议不匹配'} as any)[d.state]??'未知状态'}（网关上报）</p>)}{owner&&!g.revoked_at&&<AsyncButton className="btn-secondary" onClick={async()=>{const r=await remote<any>(path+'/'+g.id+'/revoke',{method:'POST',body:'{}'});if(isRemoteFailure(r))throw Error(r.msg);if(issued?.id===g.id)setIssued(null);await load()}}>撤销网关授权</AsyncButton>}</div>})}

  {!owner&&<div className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900" role="status">你可以在本页维护设备资料、刷牌器和播报器配置。点钟王网关配对密钥可持续访问本门店房态，仅商家老板可以签发或撤销；请由老板完成“生成只读网关授权”后再在门店电脑启动网关。</div>}
  {owner&&<><fieldset disabled={busy||!!issued} className="space-y-3">
   <h4 className="font-medium">1. 门店电脑上的网关</h4>{suggestion&&<div className="rounded border p-3"><p>检测建议：{suggestion.host}:{suggestion.port}{suggestion.deviceIds.length?` · 已授权面板 ${suggestion.deviceIds.length} 台 · 完整厂商绑定 ${suggestion.bindings.length} 项 · 本店有效房间匹配 ${suggestion.bindings.filter(b=>rooms.some(r=>r.room_no===b.roomNo&&r.active===1)).length}/${suggestion.bindings.length} · 在线IP候选 ${suggestion.panelCandidates.length} 台`:''}</p>{suggestion.bindings.filter(b=>!rooms.some(r=>r.room_no===b.roomNo&&r.active===1)).map(b=><p role="alert" className="text-sm text-amber-700" key={b.deviceId}>厂商房间 {b.roomNo} 在当前门店不存在或已停用，必须先核对房间资料。</p>)}<button className="btn-secondary" onClick={()=>{setHost(suggestion.host);setPort(String(suggestion.port));if(suggestion.deviceIds.length)setPanels(suggestion.deviceIds.map(device=>{const binding=suggestion.bindings.find(b=>b.deviceId===device),room=rooms.find(r=>r.room_no===binding?.roomNo&&r.active===1),existing=panels.find(p=>p.device.trim().toLowerCase()===device.toLowerCase());return {...emptyPanel(),device,room:binding?(room?String(room.id):''):existing?.room??'',ip:binding?.panelIp??existing?.ip??''}}))}}>应用检测到的网关参数、设备编号和房间</button></div>}
   <p className="text-sm text-gray-500">电脑地址是面板连接的服务器地址；面板IP是每台面板自己的地址，不能填反。浏览器保存配置不会启动电脑网关。</p>
   <div className="grid sm:grid-cols-3 gap-3"><label>网关名称<input className="input w-full" maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>门店电脑监听IP<input className="input w-full" value={host} onChange={e=>setHost(e.target.value)} placeholder="例如 192.168.10.254"/></label><label>网关监听端口<input className="input w-full" type="number" min={1024} max={65535} value={port} onChange={e=>setPort(e.target.value)}/></label></div>
   <p className="text-sm text-amber-700">127.0.0.1 仅供本机模拟。现场须填写门店电脑的局域网IP；默认18032，请确认未被占用，不要覆盖原厂正在使用的8032。</p>
   <h4 className="font-medium">2. 房间面板绑定（{panels.length}/100）</h4><datalist id="point-clock-panel-ip-candidates">{suggestion?.panelCandidates.map(ip=><option value={ip} key={ip}/>)}</datalist>
   {panels.map((p,i)=><div key={p.key} className="border rounded p-3 grid sm:grid-cols-4 gap-3"><label>绑定房间<select className="input w-full" value={p.room} onChange={e=>setPanels(old=>old.map(x=>x.key===p.key?{...x,room:e.target.value}:x))}><option value="">请选择本店房间</option>{rooms.filter(r=>r.active===1).map(r=><option value={r.id} key={r.id}>{r.room_no}</option>)}</select></label><label>面板IP<input className="input w-full" list="point-clock-panel-ip-candidates" value={p.ip} onChange={e=>setPanels(old=>old.map(x=>x.key===p.key?{...x,ip:e.target.value}:x))}/></label><label>设备编号<input className="input w-full" maxLength={100} value={p.device} placeholder="设备日志中的devid" onChange={e=>setPanels(old=>old.map(x=>x.key===p.key?{...x,device:e.target.value}:x))}/></label><button className="btn-secondary" disabled={panels.length===1} onClick={()=>setPanels(old=>old.filter(x=>x.key!==p.key))}>移除面板 {i+1}</button></div>)}
   <button className="btn-secondary" disabled={panels.length>=100} onClick={()=>setPanels(old=>[...old,emptyPanel()])}>添加房间面板</button>
  </fieldset>
  <AsyncButton className="btn-primary" disabled={busy||!!issued} onClick={async()=>{
   setError('');const devices=panels.map(p=>({room_id:Number(p.room),device_id:p.device.trim(),device_ip:p.ip.trim()}));const listenHost=host.trim(),listenPort=Number(port);
   if(!name.trim()||!ipv4(listenHost)||!/^((10\.)|(192\.168\.)|(172\.(1[6-9]|2\d|3[01])\.)|(127\.))/.test(listenHost)||!Number.isInteger(listenPort)||listenPort<1024||listenPort>65535){setError('请填写网关名称、有效的局域网或本机IPv4地址，以及1024–65535的端口');return}
   if(devices.some(d=>!d.room_id||!d.device_id||!ipv4(d.device_ip))){setError('每台面板都需要绑定房间、有效IPv4地址和设备编号');return}
   if(new Set(devices.map(d=>d.device_id)).size!==devices.length||new Set(devices.map(d=>d.device_ip)).size!==devices.length){setError('面板IP和设备编号不能重复');return}
   if(new Set(devices.map(d=>d.room_id)).size!==devices.length){setError('同一房间只能绑定一台点钟王面板');return}
   setBusy(true);try{const r=await remote<any>(path,{method:'POST',body:JSON.stringify({gateway_id:requestId,name:name.trim(),devices})});if(isRemoteFailure(r)){setError(r.msg);await load();return}setIssued({...r,listenHost,port:listenPort});setDownloaded(false);setRequestId(crypto.randomUUID());await load()}finally{setBusy(false)}
  }}>生成只读网关授权</AsyncButton>
  {!issued&&<button className="btn-secondary ml-2" disabled={busy} onClick={()=>{setRequestId(crypto.randomUUID());setError('')}}>开始新的授权请求</button>}
  {issued&&<div role="status" className="p-3 bg-amber-50 space-y-2"><h4>3. 在门店电脑运行网关</h4>{window.saasDesktop?.gateway&&<button className="btn-primary" disabled={localBusy||!local||local.status!=='stopped'} onClick={()=>void control('start')}>在本机启动只读网关</button>}<p>密钥仅本次可下载。配对文件包含授权，请只保存在门店电脑，不要转发。页面关闭后无法再次读取，丢失请撤销后重新生成。</p><p>监听：{issued.listenHost}:{issued.port} · 绑定 {issued.devices.length} 台面板</p><button className="btn-primary" onClick={()=>{const content={apiOrigin:getServerUrl(),listenHost:issued.listenHost,port:issued.port,storeId:issued.store_id,token:issued.token,devices:issued.devices};const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='za-thera-gateway-pairing.private.json';a.click();setDownloaded(true);setTimeout(()=>URL.revokeObjectURL(url),1000)}}>下载网关配对文件</button>{downloaded&&<button className="btn-secondary ml-2" onClick={()=>{setIssued(null);setPanels([emptyPanel()]);setDownloaded(false)}}>已保存文件，配置另一网关</button>}<p className="text-xs">新版客户端可直接启动网关，无需另装Node.js或运行命令。也可下载配对文件到独立测试网关；文件已包含监听参数。运行测试网关后查看心跳；TCP连接不等于报钟业务已接通。</p></div>}</>}
  {error&&<p role="alert" className="text-red-700">{error}</p>}
 </section>
}
