import {useEffect,useState,useRef,useId} from 'react'
import {Modal,AsyncButton} from './ui'
import PasswordInput from './PasswordInput'
export default function PlatformStores({merchant,request,onClose}:{merchant:any;request:(path:string,method?:string,body?:unknown)=>Promise<any>;onClose:()=>void}){
 const saving=useRef(false);const [working,setWorking]=useState(false)
 const [stores,setStores]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[target,setTarget]=useState<any>(null),[reason,setReason]=useState(''),[code,setCode]=useState(''),[password,setPassword]=useState(''),[result,setResult]=useState('')
 const codeHelpId=useId(),codeErrorId=useId()
 const path='/merchants/'+merchant.id+'/stores'
 async function load(){setLoading(true);try{setStores((await request(path)).items);setError('')}catch(e){setError(e instanceof Error?e.message:'读取失败')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 return <Modal open title={'门店管理 · '+merchant.name} onClose={()=>{if(!saving.current)onClose()}} width="max-w-4xl"><p className="text-sm text-gray-500 mb-4">商家：{merchant.name}（{merchant.code}）。停用可以恢复；强制删除永久生效，历史资金及审计引用保留，门店编号不再复用。</p>{error&&<p role="alert" className="text-red-600">{error}</p>}{result&&<p role="status" className="text-green-700">{result}</p>}<AsyncButton className="btn-secondary mb-3" disabled={loading||working} onClick={load}>刷新门店</AsyncButton><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>门店</th><th>状态</th><th>操作</th></tr></thead><tbody>{stores.map(s=><tr key={s.id} className="border-t"><td className="py-3">{s.name}<small className="block text-gray-500">{s.code}</small></td><td>{s.deleted_at?'已永久删除 · 不可恢复':s.status===1?'营业中':'已停用'}</td><td>{!s.deleted_at&&<div className="flex gap-2"><button className="btn-secondary" disabled={loading||working} onClick={()=>{setTarget({...s,operation:s.status===1?'disable':'restore'});setReason('');setCode('');setPassword('')}}>{s.status===1?'停用门店':'恢复门店'}</button><button className="btn-secondary text-red-600" disabled={loading||working} onClick={()=>{setTarget({...s,operation:'delete'});setReason('');setCode('');setPassword('')}}>强制删除</button></div>}</td></tr>)}</tbody></table></div>{!loading&&!stores.length&&<p>该商家尚无门店。</p>}
 <Modal open={!!target} title={target?.operation==='delete'?'永久删除门店':target?.operation==='restore'?'恢复门店':'停用门店'} onClose={()=>{if(!saving.current){setTarget(null);setPassword('')}}} footer={<><button className="btn-secondary" onClick={()=>{if(!saving.current){setTarget(null);setPassword('')}}}>取消</button><AsyncButton className={target?.operation==='delete'?'btn-danger':'btn-primary'} disabled={working||!reason.trim()||(target?.operation==='delete'&&(code!==target.code||!password))} onClick={async()=>{if(!target||saving.current)return;saving.current=true;setWorking(true);try{await request(path+'/'+target.id+'/manage','POST',{operation:target.operation,version:target.version,reason,...(target.operation==='delete'?{confirmation_code:code,current_password:password}:{})});setResult(target.operation==='delete'?'门店已永久删除，不支持恢复':target.operation==='restore'?'门店已恢复':'门店已停用');setTarget(null);setPassword('');await load()}finally{saving.current=false;setWorking(false)}}}>{target?.operation==='delete'?'确认永久删除':'确认操作'}</AsyncButton></>}><div className="space-y-4"><p>{merchant.name}（{merchant.code}） / {target?.name}（{target?.code}）</p><p className={target?.operation==='delete'?'text-red-700':'text-gray-500'}>{target?.operation==='delete'?'不可撤销：该门店将从商家端移除，员工、顾客入口及当前业务均不能继续使用。不会清空跨店资金与审计历史，技术后台也不能恢复。':target?.operation==='restore'?'恢复后原授权员工可以继续使用；商家本身已停用时仍不能营业。':'暂停该门店新营业，历史数据与员工授权保留，可由技术后台恢复。'}</p><label className="block">操作原因<textarea className="input" aria-label="门店操作原因" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{target?.operation==='delete'&&<><label className="block">请输入门店编号 <strong>{target.code}</strong> 确认<input className="input" aria-label="确认删除门店编号" name="store-deletion-confirmation-code" autoComplete="off" autoCapitalize="none" autoCorrect="off" spellCheck={false} placeholder={'请输入门店编号 '+target.code} aria-describedby={codeHelpId+(code&&code!==target.code?' '+codeErrorId:'')} aria-invalid={!!code&&code!==target.code} value={code} onChange={e=>setCode(e.target.value)}/></label><p id={codeHelpId} className="text-sm text-gray-500">这里填写门店编号，不是商家编号或平台账号。字母大小写与门店编号保持一致。</p>{!!code&&code!==target.code&&<p id={codeErrorId} role="alert" className="text-sm text-red-600">门店编号不匹配，请输入 {target.code}。</p>}<label className="block">技术后台登录密码<PasswordInput className="input" aria-label="删除确认平台密码" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><p className="text-sm text-gray-500">请输入你当前登录技术后台账号的密码。</p>{(!reason.trim()||!code||!password)&&<p role="status" className="text-sm text-gray-500">请填写操作原因、正确的门店编号和技术后台登录密码后再确认。</p>}</>}</div></Modal></Modal>
}

